### ISSUE TITLE
关于npm包和ol依赖的问题

### ISSUE THREAD

**Issue by zhangucan** [SuperMap/iClient-JavaScript#1]
你好，我是一名WebGIS初学者。请问，超图为什么不发一个npm包。当然可以使用 require('....') 导入，但我感觉还是发布一个npm包专业一点。还有就是，我在使用 for OpenLayers。请问，超图的API是openlayers 的扩展包吗？如果用require导入模块的话，怎么导入呢？

**Comment by acidgis** [comment]
npm在计划中。
在npm包出来之前，如果想模块化引用，需先下载iClient9D源码，然后参照如下方式引用具体模块：
var BaiduMap = require("iClient9/src/openlayers/mapping/BaiduMap");
注：括号中如果使用相对路径，需要将iClient9D源码拷贝至根目录下的"/node_modules/"，require具体用法参见：https://nodejs.org/api/modules.html

**Comment by caoxinke** [comment]
npm包已经上线，具体用法请参考一下链接：
https://www.npmjs.com/package/@supermap/iclient-openlayers
