### ISSUE TITLE
@supermap\iclient-common 对浏览器原生Promise造成了污染

### ISSUE THREAD

**Issue by qiangbro** [SuperMap/iClient-JavaScript#102]
### Request a feature or report a bug? [这是一个需求还是一个缺陷]
这是一个缺陷
### One-line summary [问题简述]
@supermap\iclient-common 对全局原生Promise造成了污染 。
promise-polyfill有些api的表现达不到原生Promise的性能，
我们暂时已在项目中注释掉了supermap对window.Promise的赋值操作（直接改的源代码，对不住了）。
希望supermap团队可以用更科学的办法处理promise的兼容性问题，而不是强制去赋值（如此流氓一般的操作）。
![image](https://user-images.githubusercontent.com/4646469/70330055-b2504000-1877-11ea-88d0-8f60a2eafd6a.png)
### Version [产品及版本]
+ iClient version [iClient 版本]: "@supermap/iclient-common@10.0.0

### Actual Behavior [当前现象]
浏览器原生Promise被篡改
### Expected Behavior [期望现象]
浏览器原生Promise不被篡改，除非浏览器原生不支持Promise，需要polyfill

**Comment by songyumeng** [comment]
谢谢您提的issue。
非常感谢您提的宝贵建议，我们会尽快安排修复该问题。

**Comment by songyumeng** [comment]
[promise-polyfill](https://github.com/taylorhakes/promise-polyfill/blob/master/src/polyfill.js)已处理相关逻辑，尽快安排验证并升级  [#82](https://github.com/SuperMap/iClient-JavaScript/pull/82)

**Comment by songyumeng** [comment]
这个问题已经被 02f93859f9332878332c28670acfad1f946da03e 提交修复。
10.0.1版本已带有该功能。
