### ISSUE TITLE
L.supermap.mapVLayer图层参数希望可以支持unit设置

### ISSUE THREAD

**Issue by arvenly** [SuperMap/iClient-JavaScript#103]
### One-line summary [问题简述]
L.supermap.mapVLayer(dataSet, options), options还不支持mapv图层的unit设置，目前只支持像素单位。mapV本身是支持unit设置的，可设置为px和m。
![image](https://user-images.githubusercontent.com/10769031/70893115-65adf700-2025-11ea-8850-ef9dcc8e07a3.png)

### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]: for Leaflet
+ iClient version [iClient 版本]: @10.0.0
+ Browser version [浏览器类型和版本]: chrome最新版
+ OS Version [操作系统类型和版本]:

### What is motivation or use case for changing the behavior? [需求的场景和目的是什么？]
我们产品中需要用到mapv的网格图和蜂巢图，需要支持像素单位设置和地理单位（米）设置

**Comment by songyumeng** [comment]
谢谢您报的缺陷。
这个问题已经被 [63f77f2](https://github.com/SuperMap/iClient-JavaScript/commit/63f77f2d7169daf880cc76588a7c6988273c1eab) 提交修复。
下个版本发布，或者使用 dist 下的临时版本。
