### ISSUE TITLE
graphic矢量单独对象操作建议

### ISSUE THREAD

**Issue by shouyun** [SuperMap/iClient-JavaScript#11]
### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]:for openlayers
+ iClient version [iClient 版本]:9D
+ Browser version [浏览器类型和版本]:chorme 浏览器 65.0.3325.181（正式版本） （64 位）
+ OS Version [操作系统类型和版本]:window7 旗舰版

----------

----------

### What is motivation or use case for changing the behavior? [需求的场景和目的是什么？]

graphic可以进行大数据量的渲染，支持每一个graphic矢量可以进行setId和getId。但是不能进行通过ID获取到这个graphic矢量的过程。

同时获取graphic时，应提供对单个对象的获取，编辑，删除操作。

**Comment by songyumeng** [comment]
谢谢你的建议，我们会安排优化。除了对单个对象的获取，编辑，删除，我们还会提供更新全部要素、追加要素，清空要素的方法。

**Comment by shouyun** [comment]
好的，请更新后第一时间通知我哈~ 谢谢哦

**Comment by songyumeng** [comment]
增加了 `setGraphics`  `addGraphics `  `clear `  `removeGraphics `  `getGraphicBy `  `getGraphicById` 
`getGraphicsByAttribute`等接口
