### ISSUE TITLE
引用冲突

### ISSUE THREAD

**Issue by fangchuanzhi** [SuperMap/iClient-JavaScript#12]
### One-line summary [问题简述]
在一个页面中同时引入iclient7C和 9D的mapboxgl，会出现冲突，有什么解决方案吗？
### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]:
+ iClient version [iClient 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

----------

### Example of reproducing the issue [重现现象的例子]

----------

**Comment by songyumeng** [comment]
和[#6](https://github.com/SuperMap/iClient-JavaScript/issues/6)相同问题，See [#6](https://github.com/SuperMap/iClient-JavaScript/issues/6)
