### ISSUE TITLE
for mapboxgl mapvLayer在浏览器缩放后拖动地图部分元素清除不掉

### ISSUE THREAD

**Issue by zhang6685979** [SuperMap/iClient-JavaScript#14]
### Request a feature or report a bug? [这是一个需求还是一个缺陷]
这是一个缺陷

### One-line summary [问题简述]
缩放浏览器时mapvLayer会根据devicePixelRatio进行缩放，拖动地图时会对mapv元素进行重绘，因为context的缩放导致部分元素在clear时清除不掉

### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]:
+ iClient version [iClient 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

----------

### Example of reproducing the issue [重现现象的例子]

![image](https://user-images.githubusercontent.com/4394937/40106070-594199e8-5927-11e8-87ab-025e0cbca639.png)

目前的解决办法是：
   clear时将width和height同时除以缩放比例就能解决此问题

----------

**Comment by songyumeng** [comment]
谢谢报告的缺陷。
问题已经重现，浏览器缩放比例不是100%时有两个问题 ，1、绘制位置偏移； 2 、从浏览器边界移入时部分要素没有清除。  
第一个问题引起原因应该是地理坐标转像素坐标时未考虑devicePixelRatio。
第二个问题，您的暂时解决办法是“clear时将width和height同时除以缩放比例就能解决此问题”，可以看下是否是在创建context时宽高就没有缩放。
iclient for openlayers未重现该问题，相关逻辑可以参照修改，保持一致。

**Comment by songyumeng** [comment]
@zhang6685979  定位分析问题很到位，是否可以提交一个PR？

**Comment by songyumeng** [comment]
[PR](https://github.com/SuperMap/iClient-JavaScript/pull/15)
