### ISSUE TITLE
原生API有支持高德地图的DEMO吗？

### ISSUE THREAD

**Issue by xieqian-xq** [SuperMap/iClient-JavaScript#140]
原生API有支持高德地图的DEMO吗？

**Comment by songyumeng** [comment]
谢谢您提的issue。方便我们定位和解决问题，请参照issue模板或者 描述清楚以下细节：

iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]:
iClient version [iClient 版本]:
Actual Behavior [当前现象]
Expected Behavior [期望现象]
Example of reproducing the issue [重现现象的例子]

**Comment by acidgis** [comment]
已经支持的互联网地图包括：百度、天地图、超图云，范例如下：
OpenLayers：https://iclient.supermap.io/examples/openlayers/examples.html#mapping
Leaflet：https://iclient.supermap.io/examples/leaflet/examples.html#mapping

后续会逐步增加其它互联网地图厂商DEMO，您也可以调用原生API的瓦片相关接口参考上述范例自行开发。
