### ISSUE TITLE
原生API支持电子地图、卫星地图、街景切换吗

### ISSUE THREAD

**Issue by fansichao** [SuperMap/iClient-JavaScript#147]
原生API支持电子地图、卫星地图、街景切换吗？

**Comment by songyumeng** [comment]
谢谢您提的issue。方便我们定位和解决问题，请参照issue模板或者 描述清楚以下细节：

iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]:
iClient version [iClient 版本]:
Actual Behavior [当前现象]
Expected Behavior [期望现象]
Example of reproducing the issue [重现现象的例子]

**Comment by fansichao** [comment]
iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]:
for leaflet

iClient version [iClient 版本]:
2020-03-18 最新版本

Actual Behavior [当前现象]
未找到对应API

Expected Behavior [期望现象]
需要寻找支持 切换 电子地图 卫星地图 街景地图的功能

**Comment by songyumeng** [comment]
leaflet 的 layersControl 可以满足您的需求
[https://leafletjs.com/reference-1.6.0.html#control-layers](https://leafletjs.com/reference-1.6.0.html#control-layers)

例子
https://leafletjs.com/examples/layers-control/
https://iclient.supermap.io/examples/leaflet/editor.html#controler_layerswitcher

也可以使用其他的插件库
https://github.com/search?q=leaflet+layers+control
