### ISSUE TITLE
OpenLayers 地图缩放几次之后模糊，不清楚

### ISSUE THREAD

**Issue by LCLucky** [SuperMap/iClient-JavaScript#148]
### Version [supermap iclient 10i]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]:openlayers
+ iClient version [iClient 版本]:10i
+ Browser version [浏览器类型和版本]:ie edge
+ OS Version [操作系统类型和版本]:

----------

### Example of reproducing the issue [重现现象的例子] https://iclient.supermap.io/examples/openlayers/editor.html#WMSLayer

----------

**Comment by acidgis** [comment]
IE11,Edge,Chrome均未重现此问题，截图示意一下呢

**Comment by LCLucky** [comment]
可以使用如下这段js代码，定位大概在宝鸡附近，能看到的文字是"眉县"，连续缩小级别至7级-8级，再次放大至"眉县"文字显示出来，可以看到图片显示模糊
 var resolutions = new Array(17);
    var matrixIds = new Array(17);
    for (var z = 0; z < 17; ++z) {
        resolutions[z] = 156543.033928041 / Math.pow(2, z);
        matrixIds[z] = z;
    }
    var map = new ol.Map({
        target: 'map',
        controls: ol.control.defaults({attributionOptions: {collapsed: false}})
            .extend([new ol.supermap.control.Logo()]),
        view: new ol.View({
            center: ol.proj.fromLonLat([108, 34]),
            zoom: 10,
            multiWorld: true
        }),
        layers: [new ol.layer.Tile({
            opacity: 0.7,
            source: new ol.source.TileWMS({
                url: (window.isLocal ? window.server : "https://iserver.supermap.io")+"/iserver/services/map-china400/wms111/China",
                params: {
                    'LAYERS': 'China',
                    'FORMAT': 'image/png'
                },
                attributions: "Map Data <span>© <a href='http://support.supermap.com.cn/product/iServer.aspx' target='_blank'>SuperMap iServer</a></span> with <span>© <a href='http://iclient.supermap.io' target='_blank'>SuperMap iClient</a></span>"
            }),

        })]
    });

**Comment by songyumeng** [comment]
使用您提供的代码仍然没有发现模糊的情况。一下是透明度分别是0.7和1时的截图效果。可以提供您那的截图效果看看
![透明度0 7](https://user-images.githubusercontent.com/29563916/96074104-6a0f9e80-0eda-11eb-98f0-56d6a94c2382.gif)
![透明度1](https://user-images.githubusercontent.com/29563916/96074126-78f65100-0eda-11eb-98cd-3bf0c5bd5773.gif)
