### ISSUE TITLE
GetFeaturesServiceBase.js中不能执行跨域请求

### ISSUE THREAD

**Issue by zhouLion** [SuperMap/iClient-JavaScript#16]
![image](https://user-images.githubusercontent.com/19882767/40710887-6fc5569a-642c-11e8-9c13-9744ca61921e.png)

### Request a feature or report a bug? [这是一个需求还是一个缺陷]
缺陷
### One-line summary [问题简述]
supermap中的GetFeaturesServiceBase.js的165行， http请求的method被写死为POST方法，这导致后续的代码不能执行跨域请求，望修正。
### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]:
+ iClient version [iClient 版本]:
+ Browser version [Chorme]:
+ OS Version [Win10]:

----------

### Example of reproducing the issue [重现现象的例子]

----------

**Comment by songyumeng** [comment]
谢谢您报的缺陷。
这个问题已经被 [7873a46](https://github.com/SuperMap/iClient-JavaScript/commit/7873a460e2cc3a7a1c0a43f56c88c4808b9670ec#diff-1e40243dc4c03d63b7c4681c31628928)提交修复。
iClient默认服务器(iServer)是支持‘CORS’标准，支持跨域请求的。
若服务器不支持跨域请求，需在发送请求前全局设置`SuperMap.setCORS(false);` 。
下个版本上线，或者使用 dist 下的临时版本。
