### ISSUE TITLE
请问要怎么在请求WFS或WMS的请求头中添加信息

### ISSUE THREAD

**Issue by YinDake** [SuperMap/iClient-JavaScript#162]
目前我们正在使用geoserver服务器作为地图的发布服务器，需要使用iClient JavaScript对geoserver进行交互，但是我们的geoserver在访问上进行了访问权限的限制，需要使用basic Authentication进行验证才能访问到相关的服务，请问iClient需要怎么才能够把验证信息添加到访问的Headers信息中？我们用了很长时间也没有找到相关的接口和文档说明，请问要怎么弄？

**Comment by songyumeng** [comment]
谢谢您提的issue，请参照issue模板提issue 或者 描述清楚以下细节，方便我们快速定位并解决问题：

iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]:
iClient version [iClient 版本]:
Actual Behavior [当前现象]
Expected Behavior [期望现象]
Example of reproducing the issue [重现现象的例子]

**Comment by helion2017** [comment]
> 谢谢您提的issue，请参照issue模板提issue 或者 描述清楚以下细节，方便我们快速定位并解决问题：
> 
> iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]:
> iClient version [iClient 版本]:
> Actual Behavior [当前现象]
> Expected Behavior [期望现象]
> Example of reproducing the issue [重现现象的例子]

iClient classic
iClient 8c
第三方地图服务需要在请求头加入basic Authentication进行验证，API文档中没有加入请求头的方法，也不知道怎么继承来写。
期望API支持加入请求头的参数，或者告知如何继承API加入请求头。

**Comment by songyumeng** [comment]
请提供代码片段，具体是怎么使用iclient8C的，调用的是wms wfs的哪些接口。谢谢
