### ISSUE TITLE
echartsLayer使用remove方法移除图层后，再操作地图出现报错

### ISSUE THREAD

**Issue by chaoliuchn** [SuperMap/iClient-JavaScript#18]
### Request a feature or report a bug? [这是一个需求还是一个缺陷]
缺陷
### One-line summary [问题简述]
iclient9-leaflet.js  中echartsLayer使用remove方法移除图层后，再操作地图报错
### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]:iClient for leaflet
+ iClient version [iClient 版本]: v9.0.1
+ Browser version [浏览器类型和版本]: Google Chrome 版本 67.0.3396.99
+ OS Version [操作系统类型和版本]: windows 10 

----------

### Actual Behavior [当前现象]
在地图上添加了一个echartsLayer迁徙图层后，再使用remove方法移除该图层后，再进行地图的拖拽操作；浏览器控制台出现错误信息：`Uncaught TypeError: Cannot read property 'containerPointToLayerPoint' of null`，同时再次添加一个echartsLayer在地图上会出现地图无法拖拽假死现象，影响地图的其他交互操作。

### Expected Behavior [期望现象]
图层清除后，操作正常
### Example of reproducing the issue [重现现象的例子]
官网例子：http://iclient.supermapol.com/examples/leaflet/editor.html#echartsGeoLines

----------

**Comment by songyumeng** [comment]
9.1.0-alpha版本已修复。可以在[站点](http://iclient.supermap.io/web/download/download.html#stable) 或 [github release](https://github.com/SuperMap/iClient-JavaScript/releases/tag/9.1.0-alpha)下载最新包。
