### ISSUE TITLE
RestMap查询多个数据集及RestData查询多个数据集结果无法区分是哪一个数据集的结果且字段别名丢失

### ISSUE THREAD

**Issue by zzhf** [SuperMap/iClient-JavaScript#19]
### Request a feature or report a bug? [这是一个需求还是一个缺陷]
缺陷
### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]: 
+ iClient version [iClient 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

----------

### Actual Behavior [当前现象]
* restMap只能查询一个数据集
* restData查询多个数据集结构混乱且数据集别名丢失
### Expected Behavior [期望现象]
* restMap查询多个数据集
* restData查询多个数据集返回结果类似restmap且字段别名不丢失
### Example of reproducing the issue [重现现象的例子]

<http://iclient.supermap.io/dev/examples/leaflet/editor.html#01_mapQueryBySQL>restMap无法查询多个数据集
<http://iclient.supermap.io/dev/examples/leaflet/editor.html#02_getFeatureBySQL>restData查询多个数据集结构错乱
----------

### What is motivation or use case for changing the behavior? [需求的场景和目的是什么？]
* 点选/框选restmap可查询出对应的地块

**Comment by songyumeng** [comment]
**`QueryBySQLParameters`  支持传入多个 `queryParams` 查询参数来支持多数据集查询的** 。详见 [API](http://iclient.supermap.io/dev/docs/leaflet/SuperMap.QueryBySQLParameters.html)

code:
![image](https://user-images.githubusercontent.com/29563916/42304966-66f43d56-805b-11e8-9df3-e18636b04769.png)

result:
![image](https://user-images.githubusercontent.com/29563916/42305006-8aed5846-805b-11e8-8629-b6e4b3dfb163.png)


**`GetFeaturesBySQLParameters` 是通过传多个 `datasetNames` 来支持多数据集查询的**。详见 [API](http://iclient.supermap.io/dev/docs/leaflet/SuperMap.GetFeaturesBySQLParameters.html) 

code:
![image](https://user-images.githubusercontent.com/29563916/42308177-6814210e-8067-11e8-8583-0db74238742a.png)

result:
![image](https://user-images.githubusercontent.com/29563916/42308207-7f882fd8-8067-11e8-9fc4-44fbf75b10c6.png)

请求返回结果与 SuperMap iServer 保持一致。如果觉得不满足你的需求，请联系 [超图技术支持](http://support.supermap.com.cn/) 提需求。
