### ISSUE TITLE
restMap查询返回geojson格式丢失字段别名

### ISSUE THREAD

**Issue by zzhf** [SuperMap/iClient-JavaScript#20]
### Request a feature or report a bug? [这是一个需求还是一个缺陷]
* 需求
### One-line summary [问题简述]
* restMap查询返回geojson格式丢失字段别名
### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]: dev
+ iClient version [iClient 版本]: dev
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

----------

### Actual Behavior [当前现象]
restMap查询geojson返回格式无字段别名
### Expected Behavior [期望现象]
restMap查询geojson返回格式含字段别名
### Example of reproducing the issue [重现现象的例子]

----------

### What is motivation or use case for changing the behavior? [需求的场景和目的是什么？]
restMap查询展示查询结果字段以别名为准

**Comment by songyumeng** [comment]
`SuperMap.QueryParameters` 及其子类新增 `options.returnFeatureWithFieldCaption` 参数,支持指定返回的查询结果要素字段标识为字段别名
将该参数设置为true即可。
提交：[37dfa71](37dfa712a92dc950e6daec41dd3632969acb3895)
下个版本发布，或者使用 [dist ](https://github.com/SuperMap/iClient-JavaScript/tree/master/dist)下的临时版本。
