### ISSUE TITLE
mapv格网图在不同的api文件下拖拽地图格网重绘现象不一致

### ISSUE THREAD

**Issue by chaoliuchn** [SuperMap/iClient-JavaScript#21]
### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]: iClient for leaflet
+ iClient version [iClient 版本]: v9.0.1
+ Browser version [浏览器类型和版本]: Google Chrome 版本 67.0.3396.99
+ OS Version [操作系统类型和版本]: windows 10

----------

### Actual Behavior [当前现象]
   在[官网示例](http://iclient.supermap.io/9.0.1/examples/leaflet/editor.html#ESHeatMap)中加载mapv格网图（这个示例需要将时间空间暂定）后，再进行地图的拖拽，格网不会出现重绘；而如果将这个示例使用的iclient9-leaflet.min.js文件替换为从github上下载的最新文件，进行相同个的操作，格网图就会出现重绘。两个不同的iclient9-leaflet.min.js文件，一个是官网示例中的，一个是github上的，一个会出现格网重绘，一个不会出现格网重绘。
### Expected Behavior [期望现象]
     不同的api文件，加载格网图后，拖拽地图，格网不再进行重绘。
### Example of reproducing the issue [重现现象的例子]

----------

**Comment by songyumeng** [comment]
已经被[a29b755](https://github.com/SuperMap/iClient-JavaScript/commit/a29b7550e81a3d719af0dd176c80b697cb1ab496)提交修复
请使用[9.1.0-beta](https://github.com/SuperMap/iClient-JavaScript/releases/tag/9.1.0-beta)版， 或等待下个版本发布，或者使用 [dist ](https://github.com/SuperMap/iClient-JavaScript/tree/master/dist)下的临时版本。
