### ISSUE TITLE
VectorTileSuperMapRest支持其他坐标

### ISSUE THREAD

**Issue by Luooooooo** [SuperMap/iClient-JavaScript#213]
### Request a feature or report a bug? [这是一个需求还是一个缺陷]
需求
### One-line summary [问题简述]
VectorTileSuperMapRest没有坐标设置
### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]:openlayers
+ iClient version [iClient 版本]:10.1.0-beta
+ Browser version [浏览器类型和版本]:谷歌最新
+ OS Version [操作系统类型和版本]:win10
----------

### Expected Behavior [期望现象]
支持其他动态的坐标
### Example of reproducing the issue [重现现象的例子]

----------

**Comment by songyumeng** [comment]
谢谢您提的issue。

您提到的其他坐标是指的其他坐标系吗？

[VectorTileSuperMapRest](https://iclient.supermap.io/docs/openlayers/ol.source.VectorTileSuperMapRest.html) 继承 [ol/source/VectorTile](https://openlayers.org/en/v6.4.3/apidoc/module-ol_source_VectorTile-VectorTile.html)，ol/source/VectorTile有 `projection` 参数，详见[链接](https://openlayers.org/en/v6.4.3/apidoc/module-ol_source_VectorTile-VectorTile.html), VectorTileSuperMapRest 也可以设置该参数

例子：
https://iclient.supermap.io/examples/openlayers/editor.html#mvtvectorlayer_mbstyle_4326  （EPSG:4326）
https://iclient.supermap.io/examples/openlayers/editor.html#mvtvectorlayer_mbstyle_landuse （EPSG:2362）

**Comment by Luooooooo** [comment]
![image](https://user-images.githubusercontent.com/29565303/96202290-668b1e80-0f91-11eb-8a6c-5c0eff6cda59.png)
嗯，我是看API没有写的，以为没有的。

**Comment by Luooooooo** [comment]
请问矢量图层可以设置minZoom和maxZoom吗

**Comment by songyumeng** [comment]
和`projection `参数类似，都是在父类参数中 
https://openlayers.org/en/v6.4.3/apidoc/module-ol_source_VectorTile-VectorTile.html
![image](https://user-images.githubusercontent.com/29563916/96202647-4f98fc00-0f92-11eb-8105-357e703ed748.png)

可以通过这里跳转
![image](https://user-images.githubusercontent.com/29563916/96202664-5c1d5480-0f92-11eb-9fe9-4309fcae0efc.png)

**Comment by Luooooooo** [comment]
设置了最大最小zoom，不起作用

**Comment by songyumeng** [comment]
可以试试将minZoom和maxZoom设置给VectorTileLayer

另外使用矢量瓦片在SuperMap 10i产品中，我们更建议使用[MVT](https://docs.mapbox.com/vector-tiles/specification/)+[Mapbox Style](https://docs.mapbox.com/mapbox-gl-js/style-spec/)这个方式。

代码重点片段：
![image](https://user-images.githubusercontent.com/29563916/96204256-75280480-0f96-11eb-8bec-47ebdd21de2f.png)

相关例子：
https://iclient.supermap.io/examples/openlayers/examples.html#viz-vectorTileLayer

**Comment by Luooooooo** [comment]
好的，谢谢
