### ISSUE TITLE
隐藏的mapvLayer在拖动地图或缩放地图之后会自动显示出来

### ISSUE THREAD

**Issue by zhang6685979** [SuperMap/iClient-JavaScript#22]
### Request a feature or report a bug? [这是一个需求还是一个缺陷]
这是一个缺陷
### One-line summary [问题简述]
由于业务需要我先将mapvLayer隐藏，然后拖动地图或缩放地图，隐藏的图层会被显示出来

### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]:for mapboxgl
+ iClient version [iClient 版本]:9.1.0-alpha.1
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:windows

----------

### Actual Behavior [当前现象]
拖动地图之后会把隐藏的图层显示出来
### Expected Behavior [期望现象]
拖动地图之后不显示隐藏的图层
### Example of reproducing the issue [重现现象的例子]

----------

### What is motivation or use case for changing the behavior? [需求的场景和目的是什么？]

![image](https://user-images.githubusercontent.com/4394937/42926531-4d5eb948-8b64-11e8-94dc-36b0aa14ecf3.png)
需要将源码中直接调用show方法的地方根据条件判断

**Comment by songyumeng** [comment]
下个版本发布，或者使用 [dist ](https://github.com/SuperMap/iClient-JavaScript/tree/master/dist)下的临时版本。
