### ISSUE TITLE
iClient-ol打包文件过于庞大的问题，

### ISSUE THREAD

**Issue by 2496772010** [SuperMap/iClient-JavaScript#238]
由于你们import类或者方法的方式，导致打包的时候将不需要的文件一同打包到最后的js文件中，可能需要你们重新休整那些类似图片里面的导入方式的代码，重新从单独的类文件导入，减少不必要的打包。
import { Unit, ServerType, SecurityManager, Credential, ServerGeometry, CommonUtil } from '@supermap/iclient-common';
![image](https://user-images.githubusercontent.com/46257447/106229217-11b1a200-6228-11eb-83cb-dec1d4495f97.png)

**Comment by songyumeng** [comment]
谢谢您的issue，该优化正在规划中。

**Comment by 2496772010** [comment]
已经看到你们在这方面的优化，感谢你们的优化和更新。
