### ISSUE TITLE
移除echartsLayer后地图监听事件失效

### ISSUE THREAD

**Issue by chaoliuchn** [SuperMap/iClient-JavaScript#24]
### Request a feature or report a bug? [这是一个需求还是一个缺陷]
缺陷
### One-line summary [问题简述]
iclient9-leaflet.js 移除echartsLayer后地图监听事件失效
### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]: iclient9-leaflet
+ iClient version [iClient 版本]:   v9.1.0-beta
+ Browser version [浏览器类型和版本]: chrome  68.0.3440.106
+ OS Version [操作系统类型和版本]: windows 10

----------

### Actual Behavior [当前现象]
对添加的echartsLayer图层进行移除之后，在地图初始化后通过map.on('zoomend',function(e){
})对地图添加的监听事件失效。
### Expected Behavior [期望现象]
移除echartsLayer图层,地图监听事件正常
### Example of reproducing the issue [重现现象的例子]

----------

**Comment by songyumeng** [comment]
谢谢您报的缺陷。
这个问题已经被 [8a3e843](https://github.com/SuperMap/iClient-JavaScript/commit/8a3e84317b7bb4b47ff688e732b91c7d55759b86) 提交修复。
下个版本发布，或者使用 [dist](https://github.com/SuperMap/iClient-JavaScript/tree/master/dist) 下的临时版本。
