### ISSUE TITLE
关于iclient-openlayers下面的MapExtend.js

### ISSUE THREAD

**Issue by llf-yuanchen** [SuperMap/iClient-JavaScript#26]
### Request a feature or report a bug? [这是一个需求还是一个缺陷]
bug
### One-line summary [问题简述]
当我的layer是放在openlayers提供的LayerGroup里面的时候，this.getLayers().getArray()返回的不是一个ol.layer.Base，而是一个LayerGroup，这个时候后面的一系列都会报错，望及时处理修复
### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]:openlayers
+ iClient version [iClient 版本]:9.1.0-beta
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

----------

### Example of reproducing the issue [重现现象的例子]

----------

**Comment by songyumeng** [comment]
谢谢您报的缺陷，可以提供一个简单的例子重现该问题吗？

**Comment by llf-yuanchen** [comment]
![image](https://user-images.githubusercontent.com/32414874/45868089-81d9ce80-bdb7-11e8-80c5-99c5d9fa39a7.png)


就是这里，如果在openlayers中使用了ol.layer.Group来对图层进行分组添加，在鼠标在地图上移动时会跳到这里，提示
![image](https://user-images.githubusercontent.com/32414874/45868130-9a49e900-bdb7-11e8-89a1-700302499ee4.png)
，
是因为layers = this.getLayers().getArray()；里面还会存在ol.layer.Group; ol.layer.Group.getLayers()才会取到里面的所有layer,才能去调用getSource();
所以这里希望能够完善一下，在这里我临时处理的方法是这样的
![img](https://user-images.githubusercontent.com/32414874/45868582-be59fa00-bdb8-11e8-8d9a-b888262ae436.png)



可能只是针对这种情况做的特殊处理，不知道在openlayers里面这一块还有没有其他特殊情况，还请处理完善
