### ISSUE TITLE
iclient9-leaflet-es6.js和iclient9-leaflet.js有什么区别吗？

### ISSUE THREAD

**Issue by alanwhy** [SuperMap/iClient-JavaScript#27]
### Request a feature or report a bug? [这是一个需求还是一个缺陷]
一个问题
### One-line summary [问题简述]
iclient9-leaflet-es6.js和iclient9-leaflet.js有什么区别吗？
### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]:最新
+ iClient version [iClient 版本]:最新
+ Browser version [浏览器类型和版本]:chrome69
+ OS Version [操作系统类型和版本]:window10 64

----------

### Actual Behavior [当前现象]
某个功能用不带es6的有问题，带es6的没问题
### Expected Behavior [期望现象]
解决问题
### Example of reproducing the issue [重现现象的例子]

----------

**Comment by songyumeng** [comment]
iclient9-leaflet-es6.js 是iclient9-leaflet的ES6版本，里面包括ES6新语法，浏览器不一定完全支持，详细情况见[https://kangax.github.io/compat-table/es6/](https://kangax.github.io/compat-table/es6/)
iclient9-leaflet.js 是经过bebel编辑后的版本，可以支持更多的浏览器。

可以具体说明哪些功能iclient9-leaflet.js有问题吗？
另外我们今天发布了[910](https://github.com/SuperMap/iClient-JavaScript/releases/tag/9.1.0)版本，可以使用最新版本确定问题。[下载链接](http://iclient.supermap.io/web/download/download.html)。

**Comment by alanwhy** [comment]
可以看下这个：http://ask.supermap.com/37826，用es6的不会存在这样的问题

**Comment by songyumeng** [comment]
该bug910版本已修复。
