### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by gengyanlei** [SuperMap/iClient-JavaScript#282]
![1634458278](https://user-images.githubusercontent.com/22360785/137618122-96416e6e-dea8-4ad6-a0bb-a79e9d48b1a9.jpg)

你好，请问超图的这套开源平台，对于iserver等红框内的组件 是否开源免费使用呢？

**Comment by gengyanlei** [comment]
如果不开源免费iserver红框的东西，那你这个就完全不能用。

**Comment by acidgis** [comment]
>>> 红框部分是超图云GIS服务器和在线GIS平台系列商业产品，不开源，开源的是iClient JavaScript客户端产品，iClient JavaScript是超图云GIS服务器和在线GIS平台的统一WebGIS客户端。
>>> iClient JavaScript不仅对接了超图系列商业产品的服务，并开放了配套的JavaScript接口，也开放了可视化和计算库相关接口，以及Web组件库和模板库，非商业平台用户也可以接入使用，没有限制非要购买超图的商业平台。
>>> 例如：在基础图层部分您可以接入开源服务器GeoServer或者互联网在线地图，在可视化部分使用iClient可视化图层，这是其中一项使用场景。

**Comment by gengyanlei** [comment]
好的，谢谢解答。
