### ISSUE TITLE
监听echartsLayer上的点击事件

### ISSUE THREAD

**Issue by mzy2240** [SuperMap/iClient-JavaScript#29]
### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]: iClient-leaflet
+ iClient version [iClient 版本]: ^9.10
+ Browser version [浏览器类型和版本]: Chrome 70.0.3538.102 (64bit)
+ OS Version [操作系统类型和版本]: Windows 10 Pro

----------

### Example of reproducing the issue [重现现象的例子]

----------

### What is motivation or use case for changing the behavior? [需求的场景和目的是什么？]
使用L.supermap.echartsLayer添加的scatter和lines无法响应鼠标点击事件，请问你们会考虑添加此feature吗？或者有什么work around的方法？ 谢谢！
从pure echarts 转到supermap echartslayer，需要保留原来的鼠标点击事件，但并没有在map的点击事件中找到能指向被点击的echarts元素的任何线索。

**Comment by songyumeng** [comment]
谢谢您提的缺陷。
可以用过这样获取点击的要素：
` var layer = L.supermap.echartsLayer(option).addTo(map);
  layer.getEcharts().on('click',function(result){
       console.log(result);
  });`
得到的结果是：
![image](https://user-images.githubusercontent.com/29563916/48931997-4765ec80-ef34-11e8-906b-a49e1422365d.png)

不知道是不是满足您的需求？如果不满足的话，可以提供一个重现您问题的简单demo，方便我们处理。
