### ISSUE TITLE
npm run dev打开后 没看到地图

### ISSUE THREAD

**Issue by dyh333** [SuperMap/iClient-JavaScript#291]
![image](https://user-images.githubusercontent.com/1221313/142839041-bceea27e-6a5f-426d-a4fb-dce64a39fd5d.png)

**Comment by dyh333** [comment]
是vue-iclient工程

**Comment by songyumeng** [comment]
vue-iclient工程中的demo代码，可以自己修改
具体示例请关注我们官网：
示例：https://iclient.supermap.io/examples/component/examples.html#vuecomponents_mbgl
storybook：https://iclient.supermap.io/web/storybook/vue/index.html
