### ISSUE TITLE
mapbox什么时候升级2.x呢

### ISSUE THREAD

**Issue by Luooooooo** [SuperMap/iClient-JavaScript#293]
### Request a feature or report a bug? [这是一个需求还是一个缺陷]
需求
### One-line summary [问题简述]
mapbox什么时候升级2.x呢？是否配套支持生产rgbdem？
### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]:mapboxgl
+ iClient version [iClient 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:
无
----------

### Example of reproducing the issue [重现现象的例子]

----------

### What is motivation or use case for changing the behavior? [需求的场景和目的是什么？]
减小cesium场景过大，数据过多。在小场景里可以展示好的三维效果

**Comment by acidgis** [comment]
由于MapboxGL V2版本授权协议变更，SuperMap iClient for MapboxGL 依旧会基于 V1版本进行后续版本的维护与升级，协议无变化

**Comment by Luooooooo** [comment]
> 

那可以换到[maplibra](https://github.com/maplibre/maplibre-gl-js)吗？
