### ISSUE TITLE
report a bug："export 'default' (imported as 'echarts') was not found in 'echarts'

### ISSUE THREAD

**Issue by liugx2018** [SuperMap/iClient-JavaScript#294]
warning  in ./node_modules/@supermap/iclient-common/components/chart/ChartView.js

"export 'default' (imported as 'echarts') was not found in 'echarts'

**Comment by aboutUU** [comment]
我也有相同的问题，貌似是echarts的版本太高了。期望能够兼容

**Comment by songyumeng** [comment]
谢谢您报的issue，可否提供下步骤及版本信息呢。

**Comment by aboutUU** [comment]
我们当前用的echarts版本是5.2.0，当我把echarts版本降到4.x时就没这个问题了。您可以试一下，看是否能兼容到5.2.0，谢谢

**Comment by liy9426** [comment]
也有相同的问题, 但是echart不能降级了, 期望能够兼容

**Comment by Baojiaming** [comment]
我也有相同的问题, echart不能降级了, 期望能够兼容

**Comment by songyumeng** [comment]
支持echarts5正在规划中

**Comment by BATTLEHAWK00** [comment]
#384
