### ISSUE TITLE
npm Uncaught SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by GuoyhBaron** [SuperMap/iClient-JavaScript#30]
### Request a feature or report a bug? [这是一个需求还是一个缺陷]
bug
### One-line summary [问题简述]
npm 引用 @supermap/iclient-classic ，按照官网的例子，提示报错Uncaught SyntaxError: Unexpected token export
### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]:iclient-classic
+ iClient version [iClient 版本]:9.1.0
+ Browser version [浏览器类型和版本]:node 8.12.0
+ OS Version [操作系统类型和版本]:windows 8

----------

### Actual Behavior [当前现象]
Uncaught SyntaxError: Unexpected token export
### Example of reproducing the issue [重现现象的例子]
es6+node开发，参照官网的例子
npm 引用 @supermap/iclient-classic 后，报错Uncaught SyntaxError: Unexpected token export
    at createScript (vm.js:80)
    at Object.runInThisContext (vm.js:139)
    at Module._compile (module.js:606)
    at Object.Module._extensions..js (module.js:653)
    at Module.load (module.js:561)
    at tryModuleLoad (module.js:504)
    at Function.Module._load (module.js:496)
    at Module.require (module.js:586)
    at require (internal/module.js:11)
    at eval (iclient-classic"?bb18:1)
在npm.runkit上也会报错
![image](https://user-images.githubusercontent.com/33087543/50208752-02a36900-03ad-11e9-9989-f464673b0738.png)

----------

**Comment by songyumeng** [comment]
谢谢您报的缺陷。

iclient-classic源码中使用了ES6语法，需要在打包时引入babel，可以参照iclient-leaflet的[相关介绍 ](http://iclient.supermap.io/web/introduction/leafletDevelop.html#Ready)
![image](https://user-images.githubusercontent.com/29563916/50397366-eb98b880-07aa-11e9-82f4-faf97a81ffb7.png)

另外，也可使用  var iclient = require('@supermap/iclient-classic/dist/iclient-classic.js'); 引入通过babel转换好的js。

希望能解决您的问题。

**Comment by GuoyhBaron** [comment]
感谢回复，现在采用的是直接引用打包好的js

项目本身支持es6语法，也尝试用es2015转一下，include那里也加了，但依然导入报错
