### ISSUE TITLE
@supermap/iclient-common 是否提供CDN版本

### ISSUE THREAD

**Issue by LancerSung** [SuperMap/iClient-JavaScript#300]
@supermap/iclient-common 引入后业务daim 打包太过庞大，这个包是否有CDN版本供开发者通过外链引入

**Comment by songyumeng** [comment]
暂未提供@supermap/iclient-common的cdn地址。
iclient-leaflet  iclient-ol 等库都支持cdn引入方式。
如果你仅想和iserver交互而不想引入其他地图库，可以试试[iclient-classic](https://iclient.supermap.io/examples/classic/examples.html#query)
