### ISSUE TITLE
自定义vector图层，不能正确触发styleFunction

### ISSUE THREAD

**Issue by polixiaohai** [SuperMap/iClient-JavaScript#31]
###  描述
> 不能触发style Function方法

### Version 911
+ iClient product :for openlayers
+ iClient version [iClient 版本]:911
+ Browser version [浏览器类型和版本]:chrome 70
+ OS Version [操作系统类型和版本]: win10

### Actual Behavior [当前现象]
ol.layer.Test = function (opt_options) {
    var options = opt_options ? opt_options : {};
    options.source = new ol.source.Vector({features: opt_options.features});

    ol.layer.Vector.call(this, options);
    this.setStyle(function (fea, resolution) {
        var style;
        return style;
    }.bind(this));

    // this.getSource().addFeatures(options.features);
    delete  opt_options.features;
}

ol.inherits(ol.layer.Test, ol.layer.Vector);
/// 其他方法……

### Expected Behavior [期望现象]
调用后触发this.setStyle中的匿名函数。但是在这个版本中没有触发，原生ol-v4.6.5版本可以触发。
### Example of reproducing the issue [重现现象的例子]

var map = new ol.Map({
        target: 'map',
        layers: [
            new ol.layer.Tile({
                source: new ol.source.Tianditu({})
            }),
            new ol.layer.Test({
                features: [new ol.Feature({
                    geometry: new ol.geom.Point([102.79071213226318, 25.00734961509705])
                    id: '234'
                })]
            })
        ],
        view: new ol.View({
            projection: 'EPSG:4326',
            center: [102.79071213226318, 25.00734961509705],//[102.7043, 24.9796],
            zoom: 17,
        }),
        projection: 'EPSG:4326',
    });

**Comment by songyumeng** [comment]
谢谢您提的缺陷。
我把您的代码复制在线调试，是可以正常运行的。效果见下图
![image](https://user-images.githubusercontent.com/29563916/51103364-63dc2200-181d-11e9-88c0-53e0bd71683f.png)

请再检查下代码呢。如果还是有问题，可以提供一个完成的重现demo吗？
