### ISSUE TITLE
ERROR in ./node_modules/elasticsearch/src/lib/utils.js

### ISSUE THREAD

**Issue by AJJackGIS** [SuperMap/iClient-JavaScript#32]
在angular7.x环境下 使用 leaflet

按照文档中说明的方式 https://www.npmjs.com/package/@supermap/iclient-leaflet

在编译时，报了这个错误

`ERROR in ./node_modules/elasticsearch/src/lib/utils.js
Module not found: Error: Can't resolve 'path' in 'D:\******\node_modules\elasticsearch\src\lib'
Failed to compile.`

**Comment by cuiwenting** [comment]
I had the same problem.

**Comment by songyumeng** [comment]
谢谢您提的issue
最新版本@supermap/iclient-leaflet@10.1.0是否仍有此问题。
若仍有问题请提供更详细demo或者代码、配置信息。
