### ISSUE TITLE
echarts-gl for leaflet and multiple stripcharts

### ISSUE THREAD

**Issue by mzy2240** [SuperMap/iClient-JavaScript#35]
### Request a feature or report a bug? [这是一个需求还是一个缺陷]
Two features request
### One-line summary [问题简述]
1. echarts-gl support for leaflet (like the global wind example for mapbox-gl)
2. Multiple echarts widgets show up simultaneously on the map (instead of click-n-pop or hover-n-pop)

### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]:
+ iClient version [iClient 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

----------

### Example of reproducing the issue [重现现象的例子]

----------

### What is motivation or use case for changing the behavior? [需求的场景和目的是什么？]
1. To use leaflet with echarts-gl
2. To show different dynamic line for different locations at the same time

**Comment by songyumeng** [comment]
谢谢您的issue.
1、我们暂时没有计划做 leaflet + echarts-gl，欢迎您的贡献
2、Multiple echarts widgets show up simultaneously on the map 。每一个echarts图表，或者echarts图层都是独立的，可以独立控制显隐，可以重复添加或者多次添加
如果不能解决您的问题，请您提供demo，或者线上实例 (JSFiddle/JSBin/Codepen)。谢谢。
