### ISSUE TITLE
项目中引入proj4leaflet后再引入这个包会报错No projection definition for code EPSG:4490

### ISSUE THREAD

**Issue by Face2Sun** [SuperMap/iClient-JavaScript#361]
### Request a feature or report a bug? [这是一个需求还是一个缺陷]
11.0.0版本缺陷
### One-line summary [问题简述]
项目引入proj4leaflet依赖后再引入超图依赖包就会报错，把超图依赖去掉就不会有这个问题
### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]:
+ iClient version [iClient 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

----------

### Actual Behavior [当前现象]
vue项目npm方式引入@supermap/iclient-common@11.0.0后会再使用new L.Proj.CRS('EPSG:4490', '+proj=longlat +ellps=GRS80 +no_defs', ...)会报错No projection definition for code EPSG:4490
### Expected Behavior [期望现象]
希望官方和用户们注意到这个问题及时修复，期待讨论回复
### Example of reproducing the issue [重现现象的例子]

----------

**Comment by songyumeng** [comment]
感谢您提的issue。可否麻烦您提供demo代码，或者线上实例 (JSFiddle/codesandbox)。方便我们重现及调试问题，谢谢。
