### ISSUE TITLE
请问 是否支持ol5  或者什么时候支持ol5呢？？？

### ISSUE THREAD

**Issue by lzp0070007** [SuperMap/iClient-JavaScript#37]
请问 是否支持ol5  或者什么时候支持ol5呢？？？

**Comment by acidgis** [comment]
支持的所有三方插件（包括地图库）的版本详见这里：http://iclient.supermap.io/web/introduction/overview.html#thirdpatry
ol当前使用的版本是v4.6.5
升级至5.x暂无计划

**Comment by ahnan** [comment]
ol5和ol4的api有较大变化，需要重写不少代码，欢迎热心人贡献力量

**Comment by Luooooooo** [comment]
7刚出来，可以考虑下😁

**Comment by acidgis** [comment]
ol5/6在即将发布的10i SP1版本（12月31日发布）将完成兼容，但是还会有部分ol的插件不兼容ol5/6的情况，请关注

**Comment by songyumeng** [comment]
**npm使用**
@supermap/iclient-ol 已支持ol5/6。
若使用ol4，npm 需引入@supermap/iclient-openlayers

**CDN{script标签}使用**
iclient-ol.js， 10.0.1版本后同时兼容ol4/5/6
