### ISSUE TITLE
vite开发，控制台报错

### ISSUE THREAD

**Issue by luo-geng** [SuperMap/iClient-JavaScript#376]
Uncaught TypeError: utils.inherits is not a function
    at node_modules/.pnpm/elasticsearch@16.7.2/node_modules/elasticsearch/src/lib/errors.js 
![image](https://user-images.githubusercontent.com/29565303/207530989-0b6322d8-381f-4601-85ed-c8785cd36a47.png)

建议把一些包设置为可选依赖或者peer依赖

**Comment by songyumeng** [comment]
感谢您提的issue。
iclient js支持按需引入，参考[官方文档按需引入](https://iclient.supermap.io/web/introduction/leafletDevelop.html#Modules)。
不使用按需引入可以参考[该文章](https://blog.csdn.net/supermapsupport/article/details/123569581)进行相关构建配置。

**Comment by luo-geng** [comment]
我们用的是iclient-ol的库，检查了下，发现是elasticsearch包的问题，不是按需引入的问题，建议把一些包设置为可选依赖或者peer依赖呢
