### ISSUE TITLE
增加一个纯2D-WebGL图层或者一个High Level 2D-WebGL图层比如Pixi.js

### ISSUE THREAD

**Issue by mzy2240** [SuperMap/iClient-JavaScript#38]
如题，类似的leaflet第三方图层有一些，比如https://github.com/manubb/Leaflet.PixiOverlay，能否像turf.js一样集成在supermap中呢？

**Comment by songyumeng** [comment]
谢谢您提的问题。
SuperMap iClient for Leaflet ，是基于 leaflet 开发的，并不影响其他 leaflet 插件的使用。
您可以完全按照 Leaflet.PixiOverlay 介绍的开发方式完成你想要的功能。
在iclient的基础上在直接引入
`<script src="https://cdnjs.cloudflare.com/ajax/libs/pixi.js/4.5.1/pixi.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/leaflet-pixi-overlay@1.8.1/L.PixiOverlay.min.js"></script>`
或者 
`npm install leaflet-pixi-overlay`

**Comment by ahnan** [comment]
leaflet的所有‘插件’都是可以自行添加，和iclient for leaflet库同时使用。 @songyumeng 可以在文档里面增加一个范例以告知这种使用方案。

**Comment by songyumeng** [comment]
https://iclient.supermap.io/examples/leaflet/examples.html#viz-pixi
iClient 官方增加使用 leaflet  + iclient for leaflet + L.PixiOverlay+pixi 的示例。
