### ISSUE TITLE
不兼容Openlayers7

### ISSUE THREAD

**Issue by BATTLEHAWK00** [SuperMap/iClient-JavaScript#385]
### Request a feature or report a bug? [这是一个需求还是一个缺陷]
缺陷

### One-line summary [问题简述]
![image](https://user-images.githubusercontent.com/45313304/210493511-485201f3-7b4d-4973-bc19-1ad262f00b18.png)
经查证labelCache在openlayers7版本中已被移除，导致不兼容

### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]: for openlayers
+ iClient version [iClient 版本]: 11.0.1

----------

### Example of reproducing the issue [重现现象的例子]

----------

**Comment by songyumeng** [comment]
感谢您提的issue。可否麻烦您提供demo代码，或者线上实例 (JSFiddle/codesandbox)。方便我们重现及调试问题，谢谢。
