### ISSUE TITLE
mapbox扩展如何使用

### ISSUE THREAD

**Issue by hold-baby** [SuperMap/iClient-JavaScript#41]
http://iclient.supermap.io/examples/mapboxgl/editor.html#01_tiledMapLayer_4326
这个demo看源码没有参考性  不知可有npm版的demo？
主要是不知道mapbox如何添加扩展

**Comment by alanjin** [comment]
http://iclient.supermap.io/en/web/download/download.html
这里有下载第三方库，包括mapbox的增强库

**Comment by gisshan2012** [comment]
第三方库开源吗
