### ISSUE TITLE
因为要有离线地图， 怎么使用自己的tms格式的瓦片呢

### ISSUE THREAD

**Issue by adevin** [SuperMap/iClient-JavaScript#42]

**Comment by songyumeng** [comment]
谢谢您提的issue，不过请您按照issue模板格式。
或者描述清楚以下细节，方便加快我们解决问题的速度：
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]:
+ iClient version [iClient 版本]:
Actual Behavior [当前现象]
Expected Behavior [期望现象]
Example of reproducing the issue [重现现象的例子]
