### ISSUE TITLE
包里面echart  报错 (急急急急急急急)

### ISSUE THREAD

**Issue by lovesL** [SuperMap/iClient-JavaScript#426]
### Request a feature or report a bug? [这是一个需求还是一个缺陷]
![image](https://github.com/SuperMap/iClient-JavaScript/assets/27960630/8b8c7474-4c59-4e07-944e-71c6c75d9e36)
我自己项目中也用的Echart  但是版本比较高 
### One-line summary [问题简述]
    "@supermap/iclient-ol": "^11.1.0-beta",
    "ol": "^6.14.1",
    "echarts": "5.4.0",
### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]:
+ iClient version [iClient 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

----------

### Example of reproducing the issue [重现现象的例子]

----------

**Comment by luoxiao-supermap** [comment]
我们这边没有重现，麻烦提供下完整重现demo

**Comment by lovesL** [comment]
> 我们这边没有重现，麻烦提供下完整重现demo

我用的5的版本 你们用的是4 的

**Comment by luoxiao-supermap** [comment]
解决方案：

**Comment by luoxiao-supermap** [comment]
解决方案（任选其一）：

1. 在 package.json 中加入如下配置，重新执行 npm install

```
"overrides": {
  "@supermap/iclient-common": {
    "echarts": "4.9.0"
  }
}
```

2. 给@supermap/iclient-ol配置按需引入， 参考链接 开发指南-模块化开发-按需引入部分：https://iclient.supermap.io/web/introduction/openlayersDevelop.html#Modules

3. 等下周正式版发布
