### ISSUE TITLE
与leaflet聚合插件leaflet.markercluster冲突

### ISSUE THREAD

**Issue by hold-baby** [SuperMap/iClient-JavaScript#43]
### Request a feature or report a bug? [这是一个需求还是一个缺陷]
bug
### One-line summary [问题简述]

![image](https://user-images.githubusercontent.com/21041219/60935998-3e2c6300-a2fe-11e9-9388-aff27c46d4f0.png)

![image](https://user-images.githubusercontent.com/21041219/60936035-60be7c00-a2fe-11e9-9c3e-0253c454c1a0.png)

引入后与下面的官方demo冲突
https://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.388.html

### What is motivation or use case for changing the behavior? [需求的场景和目的是什么？]

在使用iclient后实现聚合场景

**Comment by songyumeng** [comment]
谢谢您提的issue。
1、可否提供您使用的leaflet、iClient-leaflet、leaflet.markercluster的版本信息
2、可否提供更完整的你的场景下（import使用方式）重现问题的代码
那将会对我们解决问题提供很大的帮助，谢谢。

**Comment by hold-baby** [comment]
"leaflet": "^1.5.1",
"leaflet.markercluster": "^1.4.1",
"@supermap/iclient-leaflet": "^9.1.2",

js
```javascript
import L from 'leaflet'
import '@supermap/iclient-leaflet';
import { MarkerClusterGroup } from "leaflet.markercluster"
import { addressPoints } from "../src/js/mock"

var tiles = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 18,
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, Points &copy 2012 LINZ'
    }),
    latlng = L.latLng(-37.82, 175.24);

var map = L.map('map', {center: latlng, zoom: 13, layers: [tiles]});

var markers = new MarkerClusterGroup();

for (var i = 0; i < addressPoints.length; i++) {
    var a = addressPoints[i];
    var title = a[2];
    var marker = L.marker(new L.LatLng(a[0], a[1]), { title: title });
    marker.bindPopup(title);
    markers.addLayer(marker);
}

map.addLayer(markers);
```
html
```html
<!DOCTYPE html>
<html>
<head>
    <title>Leaflet debug page</title>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css" integrity="sha512-07I2e+7D8p6he1SIM+1twR5TIrhUQn9+I6yjqD53JQjFiMf8EtC93ty0/5vJTZGF8aAocvHYNEDJajGdNx1IsQ==" crossorigin="" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://leaflet.github.io/Leaflet.markercluster/example/screen.css" />
    <link rel="stylesheet" href="https://leaflet.github.io/Leaflet.markercluster/dist/MarkerCluster.css" />
    <link rel="stylesheet" href="https://leaflet.github.io/Leaflet.markercluster/dist/MarkerCluster.Default.css" />
</head>
<body>
    <div id="map"></div>
    <script src="./dist/demo.js"></script>
</body>
</html>
```

**Comment by hold-baby** [comment]
```html
其中mock的数据为
<script src="https://leaflet.github.io/Leaflet.markercluster/example/realworld.388.js"></script> -->
```

**Comment by songyumeng** [comment]
谢谢您报的issue及提供的代码。

根据您的代码，我发现问题出现在 `import ` 进来的 `addressPoints` 为 `undefined`。您可以console一下addressPoints看看。

如果您期望 `import { addressPoints } from "../src/js/mock"`  这种“导入接口“的方式导入 `addressPoints` ，`realworld.388.js`文件中的`var addressPoints = [..]`,应该写成 `export var addressPoints = [..]`

![image](https://user-images.githubusercontent.com/29563916/69034806-05736780-0a1d-11ea-8b85-4615c47fba50.png)
