### ISSUE TITLE
BUG：@supermap/iclient-common 包依赖echarts4.x版本但是package.json中没有声明该依赖

### ISSUE THREAD

**Issue by lilu0826** [SuperMap/iClient-JavaScript#434]
![image](https://github.com/SuperMap/iClient-JavaScript/assets/38303643/50a026e6-7db7-4097-9d0f-c04ed284ffcf)

### One-line summary [问题简述]:
@supermap/iclient-common 包依赖echarts4.x版本但是package.json中没有声明该依赖,导致项目在使用时必须安装4.9版本echarts不能使用5.x版本echarts

### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]: openlayers
+ iClient version [iClient 版本]:11.1.0-beta
+ Browser version [浏览器类型和版本]:chrome latest
+ OS Version [操作系统类型和版本]: windows 11

----------

### Actual Behavior [当前现象]
当项目使用echarts5.x的时候，webpack打包时会提示错误，错误语句为上诉图标位置，问题原因为@supermap/iclient-common 包依赖echarts4.x版本但是package.json中没有声明该依赖

### Expected Behavior [期望现象]
@supermap/iclient-common 在package.json中声明echarts4.x依赖，项目能正常使用echarts5.x

### Example of reproducing the issue [重现现象的例子]
webpack项目中安装echarts5.x，导入使用@supermap/iclient-ol，webpack报错。

**Comment by lilu0826** [comment]
![image](https://github.com/SuperMap/iClient-JavaScript/assets/38303643/a4f3c502-f709-4a16-874d-24445900b77c)

**Comment by lilu0826** [comment]
![image](https://github.com/SuperMap/iClient-JavaScript/assets/38303643/dc8da8f2-a9ee-4af7-88cf-4dc59227c18c)

**Comment by songyumeng** [comment]
参考#426的解决办法
11.1.0正式版npm已发布，可以使用这个版本
