### ISSUE TITLE
升级到 11.1.0报错

### ISSUE THREAD

**Issue by lovesL** [SuperMap/iClient-JavaScript#438]
### One-line summary [问题简述]
![image](https://github.com/SuperMap/iClient-JavaScript/assets/27960630/65149ff6-9f6c-4e4a-9b5d-4bac9288ea6a)

### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]:
+ iClient version [iClient 版本]:^11.1.0
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

----------

### Example of reproducing the issue [重现现象的例子]

----------

**Comment by luoxiao-supermap** [comment]
这个是因为iClient-Javascript引入的三方库所依赖的node模块缺失导致的报错。webpack5和vite默认没有包含node相关模块。
解决方案如下：
方案一： 等待11.1.1版本发布
方案二：如果使用webpack5, 可以 [配置按需引入](https://iclient.supermap.io/web/introduction/leafletDevelop.html#Modules)
方案三：安装配置对应的node模块， 以webpack5为例 ，
（1）首先安装依赖
 `npm i stream-http  https-browserify stream-browserify tty-browserify browserify-zlib os-browserify buffer url assert process events util -D `
（2）配置webpack.config.js                                           
`module.exports: {
    resolve: {
      alias: {
        process: 'process/browser',
      },
      mainFields: ['browser', 'main'],
      fallback: {
        fs: false,
        http: require.resolve('stream-http'),
        https: require.resolve('https-browserify'),
        os: require.resolve('os-browserify/browser'),
        stream: require.resolve('stream-browserify'),
        tty: require.resolve('tty-browserify'),
        zlib: require.resolve('browserify-zlib'),
        assert: require.resolve('assert'),
        util: require.resolve('util'),
        events: require.resolve('events')
      }
    }
    plugins: [
      new webpack.ProvidePlugin({
        process: 'process/browser',
        Buffer: ['buffer', 'Buffer']
      }),
    ]
}`

**Comment by godeev** [comment]
vite 的配置按需引入还是报这个错, 这样的话是不是只能等待 11.1.1 或者 回退版本到 11.0.1 啊 ?

**Comment by luoxiao-supermap** [comment]
webpack才有按需引入的配置， vite没有；
vite同样安装配置对应的node模块也可以
1.安装` npm i buffer events os-browserify util -D`
2.配置vite.config.js
```
export default defineConfig({
  define: {
    'process.env': {},
    'process.version': `''`,
  },
  resolve: {
    alias: {
      os: 'os-browserify/browser'
    },
  },
});

```

**Comment by godeev** [comment]
请问, 什么时候能升级到11.1.1呀, 能不能尽快解决这些问题, 赶紧上线

**Comment by godeev** [comment]
> webpack才有按需引入的配置， vite没有； vite同样安装配置对应的node模块也可以 1.安装` npm i buffer events os-browserify util -D` 2.配置vite.config.js
> 
> ```
> export default defineConfig({
>   define: {
>     'process.env': {},
>     'process.version': `''`,
>   },
>   resolve: {
>     alias: {
>       os: 'os-browserify/browser'
>     },
>   },
> });
> ```

这个按照您提供的方案, 本地开发没问题, 但是线上报错了
![企业微信截图_16950213961332](https://github.com/SuperMap/iClient-JavaScript/assets/36323493/ea56dce4-6578-471d-bf27-2808764b680a)

**Comment by luoxiao-supermap** [comment]
加一个 {'process.browser': `''`}
![image](https://github.com/SuperMap/iClient-JavaScript/assets/97505033/92b542c3-a650-4b0a-a942-93ec7f41a403)

**Comment by luoxiao-supermap** [comment]
加个配置：   `'process.browser': `''``
![image](https://github.com/SuperMap/iClient-JavaScript/assets/97505033/32e92eb3-c188-49ca-893c-18a7219002b4)

**Comment by luoxiao-supermap** [comment]
@godeev 
 11.1.1已经修复了这个问题， 不用再安装buffer等依赖和配置defined和alias
