### ISSUE TITLE
iClient3D没有开源

### ISSUE THREAD

**Issue by yunfei181** [SuperMap/iClient-JavaScript#44]
好像没有找到源代码，只有一个打包后的Cesium.js文件，这也叫开源？

**Comment by acidgis** [comment]
SuperMap iClient JavaScript（云GIS网络客户端开发平台） 和 SuperMap iClient3D for WebGL（三维客户端开发平台）是两条独立的产品线，后者并未开源，感谢您对超图产品的关注。
