### ISSUE TITLE
11.1.1版本   node_modules包里面的flatgeobuf 文件2.23.1版本js文件大小写不匹配冲突

### ISSUE THREAD

**Issue by qingyajie** [SuperMap/iClient-JavaScript#447]
iClient-JavaScript   升级到11.1.1版本后   node_modules包里面的flatgeobuf依赖的2.23.1版本  flatgeobuf里面的config和logger2个js文件用的大写会报大小写不匹配的错误，flatgeobuf依赖升级到2.4.0版本则会解决，麻烦解决一下，谢谢

![0UWQD AN1EI0SQB(6@~XB6Y_tmb](https://github.com/SuperMap/iClient-JavaScript/assets/51185208/26164c0e-0fa5-4aa7-8c29-1c3e3173449a)

**Comment by xilanhuaweidapao** [comment]
你好，flatgeobuf 暂时无法升级，可以先去掉对于大小写的判断处理，webpack 配置里加上config.plugins.delete('case-sensitive-paths');

**Comment by qingyajie** [comment]
谢谢，已按该方案临时解决所提问题，后续会同步更新继续验证

**Comment by dengBox** [comment]
+1

**Comment by zanjie1999** [comment]
真的逆天，解决方案
```
mv ./node_modules/.pnpm/flatgeobuf@3.23.1/node_modules/flatgeobuf/lib/mjs/Logger.js  ./node_modules/.pnpm/flatgeobuf@3.23.1/node_modules/flatgeobuf/lib/mjs/logger.js
```

**Comment by songyumeng** [comment]
@supermapgis/iclient-leaflet 11.1.2及是上版本已修复
