### ISSUE TITLE
GetFeaturesByIDsParameters 详细的id对应哪些啊

### ISSUE THREAD

**Issue by CarryM** [SuperMap/iClient-JavaScript#46]
datasetNames能不能设置到市啊

![image](https://user-images.githubusercontent.com/30335440/63826743-23d44480-c993-11e9-8975-634bfe164f8b.png)

**Comment by songyumeng** [comment]
谢谢你提的issue。不过为了方便我们更快速的定位和解决您的问题，请您下次按照issue模板提缺陷，谢谢。
SuperMap iClient的这些 `service` 和 `parameter` 是对接的[SuperMap iServer](http://support.supermap.com.cn/product/iServer.aspx)相关服务。
其中的datasetNames 、datasourceName、ids这些参数能设置些什么是和SuperMap iServer的服务和服务对应的数据有关系的。
比如说这个[例子](http://iclient.supermap.io/examples/leaflet/editor.html#02_getFeatureByIDs)，使用的是iServer的示例服务 http://support.supermap.com.cn:8090/iserver/services/data-world/rest/data，
其中datasource列表为：
http://support.supermap.com.cn:8090/iserver/services/data-world/rest/data/datasources
dataset列表为：
http://support.supermap.com.cn:8090/iserver/services/data-world/rest/data/datasources/World/datasets
可选id列表：
http://support.supermap.com.cn:8090/iserver/services/data-world/rest/data/datasources/World/datasets/Countries/features
可选值在这些里面选择。

您可以先了解一下SuperMap iServer产品的使用：http://support.supermap.com.cn:8090/iserver/help/html/zh/index.htm
谢谢。
