### ISSUE TITLE
chrome 73 以上版本。地图zoom滚动缩放js报错

### ISSUE THREAD

**Issue by xiaogaofudao** [SuperMap/iClient-JavaScript#48]
chrome 73 以上版本。地图zoom滚动缩放控制台报如下错误
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL>
超图官网classic 就有此问题。希望官方尽快修复

**Comment by songyumeng** [comment]
谢谢您报的issue，请参照issue模板提issue，方便我们快速定位并解决问题。

**Comment by songyumeng** [comment]
issue已修复。
在线地址：[http://iclient.supermap.io/libs/iclient8c/libs/SuperMap-8.1.1-17729.js](http://iclient.supermap.io/libs/iclient8c/libs/SuperMap-8.1.1-17729.js)
 也可以在[这里](https://github.com/SuperMap/iClient-JavaScript/tree/master/src/classic/libs)获取最新的iClient Classic 的 iClient 8C依赖包。
也可以在[releases](https://github.com/SuperMap/iClient-JavaScript/releases)  可以下载最新版本，在zip的`src/classic/lib`目录中。
