### ISSUE TITLE
V11.1.1版本用npm安装后出现flatgeobuf依赖文件引用大小写问题

### ISSUE THREAD

**Issue by chenjiaobin** [SuperMap/iClient-JavaScript#480]
### 环境版本
nodejs：V14.15.0
npm：V6.14.8
@supermap/iclient-ol：V11.1.1

### One-line summary [问题简述]
@supermap/iclient-ol@V11.1.1版本用npm安装后出现flatgeobuf依赖文件引用大小写问题

### 临时解决
改用yarn安装就正常，flatgeobuf/lib/mjs目录下的config.js和logger.js文件名就是正常的小写，也能正常跑起来项目

### 补充
其它电脑环境配置一直部分同学用npm安装同个版本@supermap/iclient-ol就正常，大小写也正常，但是多个同学都出现大小写问题

![image](https://github.com/SuperMap/iClient-JavaScript/assets/24197503/d570d2ec-f869-40ce-ace4-df63ff7d5aba)

**Comment by songyumeng** [comment]
see #447
