### ISSUE TITLE
maplibre-gl-enhance 的style->sources->type: 'raster'设置tileSize: 512无效

### ISSUE THREAD

**Issue by Baikaler** [SuperMap/iClient-JavaScript#487]
如题，在使用maplibre-gl-enhance，加载wtms服务时设置tileSize: 512，经验证设置为256或者不设置或者设置512，地图都只能加载256的wtms服务

**Comment by songyumeng** [comment]
谢谢你提的issue。
你是说OGC的WMTS服务吗？可以先确定下你的服务是否支持512的瓦片。
请提供下下你的代码和WMTS服务的能力文档，便于我们跟踪问题。

**Comment by Baikaler** [comment]
代码如下：坐标系使用的标准的EPSG:4498
<script type="text/javascript">
    var WKT = 'PROJCS["CGCS2000 / Gauss-Kruger zone 20",GEOGCS["China Geodetic Coordinate System 2000",DATUM["China 2000",SPHEROID["CGCS2000", 6378137.0, 298.257222101, AUTHORITY["EPSG","1024"]],AUTHORITY["EPSG","1043"]],PRIMEM["Greenwich", 0.0, AUTHORITY["EPSG","8901"]],UNIT["degree", 0.017453292519943295],AXIS["Geodetic longitude", EAST],AXIS["Geodetic latitude", NORTH],AUTHORITY["EPSG","4490"]],PROJECTION["Transverse_Mercator", AUTHORITY["EPSG","9807"]],PARAMETER["central_meridian", 117.0],PARAMETER["latitude_of_origin", 0.0],PARAMETER["scale_factor", 1.0],PARAMETER["false_easting", 20500000.0],PARAMETER["false_northing", 0.0],UNIT["m", 1.0],AXIS["Easting", EAST], AXIS["Northing", NORTH],AUTHORITY["EPSG","4498"]]';
    // var Proj4 =' +proj=tmerc +lat_0=0 +lon_0=117 +k=1 +x_0=20500000.0 +y_0=0 +ellps=GRS80 +units=m +no_defs +type=crs'
    var map = new maplibregl.Map({
        container: 'map',
        style: {
            version: 8,
            sources: {
                bj_shiliang: {
                    type: 'raster',
                    tileSize: 512,
                    tiles: [
                        "http://localhost:9090/geoserver/postgis/gwc/service/wmts?layer=postgis:bjcgcs20&style=&tilematrixset=EPSG:4498x2&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image/jpeg&TileMatrix=EPSG:4498x2:{z}&TileCol={x}&TileRow={y}",
                    ],
                },
            },
            layers: [
                 {
                     id: 'bj_shiliang',
                     type: 'raster',
                     source: 'bj_shiliang',
                     minzoom: 0,
                     maxzoom: 19
                 },
            ]
        },
        crs: new maplibregl.CRS('EPSG:4498', WKT, [20184047.248447325,2103881.962779923,20815952.751552675,5714206.250336334]),
        center: [116.5, 39.9],
		pitch: 45,
        zoom: 9,
        renderWorldCopies: false,
    });
	
	  map.addControl(new maplibregl.FullscreenControl());
      map.addControl(new maplibregl.NavigationControl());
      map.addControl(new maplibregl.ScaleControl());
</script>

**Comment by Baikaler** [comment]
使用的标准的EPSG:4498坐标系，代码如下：
<script type="text/javascript">
    var WKT = 'PROJCS["CGCS2000 / Gauss-Kruger zone 20",GEOGCS["China Geodetic Coordinate System 2000",DATUM["China 2000",SPHEROID["CGCS2000", 6378137.0, 298.257222101, AUTHORITY["EPSG","1024"]],AUTHORITY["EPSG","1043"]],PRIMEM["Greenwich", 0.0, AUTHORITY["EPSG","8901"]],UNIT["degree", 0.017453292519943295],AXIS["Geodetic longitude", EAST],AXIS["Geodetic latitude", NORTH],AUTHORITY["EPSG","4490"]],PROJECTION["Transverse_Mercator", AUTHORITY["EPSG","9807"]],PARAMETER["central_meridian", 117.0],PARAMETER["latitude_of_origin", 0.0],PARAMETER["scale_factor", 1.0],PARAMETER["false_easting", 20500000.0],PARAMETER["false_northing", 0.0],UNIT["m", 1.0],AXIS["Easting", EAST], AXIS["Northing", NORTH],AUTHORITY["EPSG","4498"]]';
    // var Proj4 =' +proj=tmerc +lat_0=0 +lon_0=117 +k=1 +x_0=20500000.0 +y_0=0 +ellps=GRS80 +units=m +no_defs +type=crs'
    var map = new maplibregl.Map({
        container: 'map',
        style: {
            version: 8,
            sources: {
                bj_dist: {
                    type: 'raster',
                    tileSize: 512,
                    tiles: [
                        "http://localhost:9090/geoserver/postgis/gwc/service/wmts?layer=postgis:bjcgcs20&style=&tilematrixset=EPSG:4498x2&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image/jpeg&TileMatrix=EPSG:4498x2:{z}&TileCol={x}&TileRow={y}",
                    ],
                },
            },
            layers: [
                 {
                     id: 'bj_dist',
                     type: 'raster',
                     source: 'bj_dist',
                     minzoom: 0,
                     maxzoom: 19
                 },
            ]
        },
        crs: new maplibregl.CRS('EPSG:4498', WKT, [20184047.248447325,2103881.962779923,20815952.751552675,5714206.250336334]),
        center: [116.5, 39.9],
		pitch: 45,
        zoom: 9,
        renderWorldCopies: false,
    });
	
	  map.addControl(new maplibregl.FullscreenControl());
      map.addControl(new maplibregl.NavigationControl());
      map.addControl(new maplibregl.ScaleControl());
</script>

**Comment by songyumeng** [comment]
你的wmts服务能出512的瓦片吗，通常情况下wmts都只是256的瓦片，请提供下你的wmts capabilities文档

**Comment by Baikaler** [comment]
Capabilities xmlns="http://www.opengis.net/wmts/1.0" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:gml="http://www.opengis.net/gml" xsi:schemaLocation="http://www.opengis.net/wmts/1.0 http://schemas.opengis.net/wmts/1.0/wmtsGetCapabilities_response.xsd" version="1.0.0">
<script/>
<ows:ServiceIdentification>
	<ows:Title>GeoServer Web Map Tile Service</ows:Title>
	<ows:Abstract>A compliant implementation of WMTS service.</ows:Abstract>
	<ows:Keywords>
		<ows:Keyword>WMTS</ows:Keyword>
	</ows:Keywords>
	<ows:ServiceType>OGC WMTS</ows:ServiceType>
	<ows:ServiceTypeVersion>1.0.0</ows:ServiceTypeVersion>
	<ows:Fees>NONE</ows:Fees>
	<ows:AccessConstraints>NONE</ows:AccessConstraints>
</ows:ServiceIdentification>
<ows:ServiceProvider>
	<ows:ProviderName>http://geoserver.org/com</ows:ProviderName>
	<ows:ProviderSite xlink:href="http://geoserver.org"/>
	<ows:ServiceContact>
		<ows:IndividualName>Claudius Ptolomaeus</ows:IndividualName>
		<ows:PositionName>Chief Geographer</ows:PositionName>
		<ows:ContactInfo>
			<ows:Address>
				<ows:City>Alexandria</ows:City>
				<ows:Country>Roman Empire</ows:Country>
				<ows:ElectronicMailAddress>claudius.ptolomaeus@mercury.olympus.gov</ows:ElectronicMailAddress>
			</ows:Address>
		</ows:ContactInfo>
	</ows:ServiceContact>
</ows:ServiceProvider>
<ows:OperationsMetadata>
	<ows:Operation name="GetCapabilities">
		<ows:DCP>
			<ows:HTTP>
				<ows:Get xlink:href="http://localhost:9090/geoserver/gwc/service/wmts?">
					<ows:Constraint name="GetEncoding">
						<ows:AllowedValues>
							<ows:Value>KVP</ows:Value>
						</ows:AllowedValues>
					</ows:Constraint>
				</ows:Get>
			</ows:HTTP>
		</ows:DCP>
	</ows:Operation>
	<ows:Operation name="GetTile">
		<ows:DCP>
			<ows:HTTP>
				<ows:Get xlink:href="http://localhost:9090/geoserver/gwc/service/wmts?">
					<ows:Constraint name="GetEncoding">
						<ows:AllowedValues>
							<ows:Value>KVP</ows:Value>
						</ows:AllowedValues>
					</ows:Constraint>
				</ows:Get>
			</ows:HTTP>
		</ows:DCP>
	</ows:Operation>
	<ows:Operation name="GetFeatureInfo">
		<ows:DCP>
			<ows:HTTP>
				<ows:Get xlink:href="http://localhost:9090/geoserver/gwc/service/wmts?">
					<ows:Constraint name="GetEncoding">
						<ows:AllowedValues>
							<ows:Value>KVP</ows:Value>
						</ows:AllowedValues>
					</ows:Constraint>
				</ows:Get>
			</ows:HTTP>
		</ows:DCP>
	</ows:Operation>
</ows:OperationsMetadata>
<Contents>
	<Layer>
		<ows:Title>北京地区</ows:Title>
		<ows:Identifier>postgis:bjcgcs20</ows:Identifier>
		<Style isDefault="true">
			<ows:Identifier>polygon</ows:Identifier>
			<LegendURL format="image/png" xlink:href="http://localhost:9090/geoserver/ows?service=WMS&request=GetLegendGraphic&format=image%2Fpng&width=20&height=20&layer=postgis%3Abjcgcs20" width="20" height="20"/>
		</Style>
		<Format>application/vnd.mapbox-vector-tile</Format>
		<Format>image/png</Format>
		<Format>image/jpeg</Format>
		<InfoFormat>text/plain</InfoFormat>
		<InfoFormat>application/vnd.ogc.gml</InfoFormat>
		<InfoFormat>text/xml</InfoFormat>
		<InfoFormat>application/vnd.ogc.gml/3.1.1</InfoFormat>
		<InfoFormat>text/xml</InfoFormat>
		<InfoFormat>text/html</InfoFormat>
		<InfoFormat>application/json</InfoFormat>
		<TileMatrixSetLink>
			<TileMatrixSet>EPSG:4498x2</TileMatrixSet>
			<TileMatrixSetLimits>
				<TileMatrixLimits>
					<TileMatrix>EPSG:4498x2:0</TileMatrix>
					<MinTileRow>2</MinTileRow>
					<MaxTileRow>2</MaxTileRow>
					<MinTileCol>0</MinTileCol>
					<MaxTileCol>0</MaxTileCol>
				</TileMatrixLimits>
				<TileMatrixLimits>
					<TileMatrix>EPSG:4498x2:1</TileMatrix>
					<MinTileRow>4</MinTileRow>
					<MaxTileRow>4</MaxTileRow>
					<MinTileCol>0</MinTileCol>
					<MaxTileCol>1</MaxTileCol>
				</TileMatrixLimits>
				<TileMatrixLimits>
					<TileMatrix>EPSG:4498x2:2</TileMatrix>
					<MinTileRow>7</MinTileRow>
					<MaxTileRow>8</MaxTileRow>
					<MinTileCol>1</MinTileCol>
					<MaxTileCol>2</MaxTileCol>
				</TileMatrixLimits>
				<TileMatrixLimits>
					<TileMatrix>EPSG:4498x2:3</TileMatrix>
					<MinTileRow>15</MinTileRow>
					<MaxTileRow>17</MaxTileRow>
					<MinTileCol>2</MinTileCol>
					<MaxTileCol>4</MaxTileCol>
				</TileMatrixLimits>
				<TileMatrixLimits>
					<TileMatrix>EPSG:4498x2:4</TileMatrix>
					<MinTileRow>30</MinTileRow>
					<MaxTileRow>34</MaxTileRow>
					<MinTileCol>4</MinTileCol>
					<MaxTileCol>9</MaxTileCol>
				</TileMatrixLimits>
				<TileMatrixLimits>
					<TileMatrix>EPSG:4498x2:5</TileMatrix>
					<MinTileRow>59</MinTileRow>
					<MaxTileRow>68</MaxTileRow>
					<MinTileCol>9</MinTileCol>
					<MaxTileCol>18</MaxTileCol>
				</TileMatrixLimits>
				<TileMatrixLimits>
					<TileMatrix>EPSG:4498x2:6</TileMatrix>
					<MinTileRow>118</MinTileRow>
					<MaxTileRow>136</MaxTileRow>
					<MinTileCol>18</MinTileCol>
					<MaxTileCol>36</MaxTileCol>
				</TileMatrixLimits>
				<TileMatrixLimits>
					<TileMatrix>EPSG:4498x2:7</TileMatrix>
					<MinTileRow>237</MinTileRow>
					<MaxTileRow>273</MaxTileRow>
					<MinTileCol>36</MinTileCol>
					<MaxTileCol>72</MaxTileCol>
				</TileMatrixLimits>
				<TileMatrixLimits>
					<TileMatrix>EPSG:4498x2:8</TileMatrix>
					<MinTileRow>473</MinTileRow>
					<MaxTileRow>546</MaxTileRow>
					<MinTileCol>73</MinTileCol>
					<MaxTileCol>145</MaxTileCol>
				</TileMatrixLimits>
				<TileMatrixLimits>
					<TileMatrix>EPSG:4498x2:9</TileMatrix>
					<MinTileRow>946</MinTileRow>
					<MaxTileRow>1092</MaxTileRow>
					<MinTileCol>146</MinTileCol>
					<MaxTileCol>290</MaxTileCol>
				</TileMatrixLimits>
				<TileMatrixLimits>
					<TileMatrix>EPSG:4498x2:10</TileMatrix>
					<MinTileRow>1891</MinTileRow>
					<MaxTileRow>2183</MaxTileRow>
					<MinTileCol>292</MinTileCol>
					<MaxTileCol>580</MaxTileCol>
				</TileMatrixLimits>
				<TileMatrixLimits>
					<TileMatrix>EPSG:4498x2:11</TileMatrix>
					<MinTileRow>3783</MinTileRow>
					<MaxTileRow>4366</MaxTileRow>
					<MinTileCol>585</MinTileCol>
					<MaxTileCol>1161</MaxTileCol>
				</TileMatrixLimits>
				<TileMatrixLimits>
					<TileMatrix>EPSG:4498x2:12</TileMatrix>
					<MinTileRow>7565</MinTileRow>
					<MaxTileRow>8731</MaxTileRow>
					<MinTileCol>1171</MinTileCol>
					<MaxTileCol>2322</MaxTileCol>
				</TileMatrixLimits>
				<TileMatrixLimits>
					<TileMatrix>EPSG:4498x2:13</TileMatrix>
					<MinTileRow>15129</MinTileRow>
					<MaxTileRow>17461</MaxTileRow>
					<MinTileCol>2342</MinTileCol>
					<MaxTileCol>4644</MaxTileCol>
				</TileMatrixLimits>
				<TileMatrixLimits>
					<TileMatrix>EPSG:4498x2:14</TileMatrix>
					<MinTileRow>30258</MinTileRow>
					<MaxTileRow>34922</MaxTileRow>
					<MinTileCol>4685</MinTileCol>
					<MaxTileCol>9288</MaxTileCol>
				</TileMatrixLimits>
				<TileMatrixLimits>
					<TileMatrix>EPSG:4498x2:15</TileMatrix>
					<MinTileRow>60515</MinTileRow>
					<MaxTileRow>69844</MaxTileRow>
					<MinTileCol>9370</MinTileCol>
					<MaxTileCol>18577</MaxTileCol>
				</TileMatrixLimits>
				<TileMatrixLimits>
					<TileMatrix>EPSG:4498x2:16</TileMatrix>
					<MinTileRow>121030</MinTileRow>
					<MaxTileRow>139687</MaxTileRow>
					<MinTileCol>18741</MinTileCol>
					<MaxTileCol>37155</MaxTileCol>
				</TileMatrixLimits>
				<TileMatrixLimits>
					<TileMatrix>EPSG:4498x2:17</TileMatrix>
					<MinTileRow>242060</MinTileRow>
					<MaxTileRow>279375</MaxTileRow>
					<MinTileCol>37482</MinTileCol>
					<MaxTileCol>74310</MaxTileCol>
				</TileMatrixLimits>
				<TileMatrixLimits>
					<TileMatrix>EPSG:4498x2:18</TileMatrix>
					<MinTileRow>484121</MinTileRow>
					<MaxTileRow>558751</MaxTileRow>
					<MinTileCol>74965</MinTileCol>
					<MaxTileCol>148620</MaxTileCol>
				</TileMatrixLimits>
				<TileMatrixLimits>
					<TileMatrix>EPSG:4498x2:19</TileMatrix>
					<MinTileRow>968243</MinTileRow>
					<MaxTileRow>1117502</MaxTileRow>
					<MinTileCol>149931</MinTileCol>
					<MaxTileCol>297240</MaxTileCol>
				</TileMatrixLimits>
			</TileMatrixSetLimits>
		</TileMatrixSetLink>
		<ResourceURL format="application/vnd.mapbox-vector-tile" resourceType="tile" template="http://localhost:9090/geoserver/gwc/service/wmts/rest/postgis:bjcgcs20/{style}/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}?format=application/vnd.mapbox-vector-tile"/>
		<ResourceURL format="image/png" resourceType="tile" template="http://localhost:9090/geoserver/gwc/service/wmts/rest/postgis:bjcgcs20/{style}/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}?format=image/png"/>
		<ResourceURL format="image/jpeg" resourceType="tile" template="http://localhost:9090/geoserver/gwc/service/wmts/rest/postgis:bjcgcs20/{style}/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}?format=image/jpeg"/>
		<ResourceURL format="text/plain" resourceType="FeatureInfo" template="http://localhost:9090/geoserver/gwc/service/wmts/rest/postgis:bjcgcs20/{style}/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}/{J}/{I}?format=text/plain"/>
		<ResourceURL format="application/vnd.ogc.gml" resourceType="FeatureInfo" template="http://localhost:9090/geoserver/gwc/service/wmts/rest/postgis:bjcgcs20/{style}/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}/{J}/{I}?format=application/vnd.ogc.gml"/>
		<ResourceURL format="text/xml" resourceType="FeatureInfo" template="http://localhost:9090/geoserver/gwc/service/wmts/rest/postgis:bjcgcs20/{style}/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}/{J}/{I}?format=text/xml"/>
		<ResourceURL format="application/vnd.ogc.gml/3.1.1" resourceType="FeatureInfo" template="http://localhost:9090/geoserver/gwc/service/wmts/rest/postgis:bjcgcs20/{style}/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}/{J}/{I}?format=application/vnd.ogc.gml/3.1.1"/>
		<ResourceURL format="text/xml" resourceType="FeatureInfo" template="http://localhost:9090/geoserver/gwc/service/wmts/rest/postgis:bjcgcs20/{style}/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}/{J}/{I}?format=text/xml"/>
		<ResourceURL format="text/html" resourceType="FeatureInfo" template="http://localhost:9090/geoserver/gwc/service/wmts/rest/postgis:bjcgcs20/{style}/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}/{J}/{I}?format=text/html"/>
		<ResourceURL format="application/json" resourceType="FeatureInfo" template="http://localhost:9090/geoserver/gwc/service/wmts/rest/postgis:bjcgcs20/{style}/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}/{J}/{I}?format=application/json"/>
	</Layer>
	<TileMatrixSet>
		<ows:Identifier>EPSG:4498x2</ows:Identifier>
		<ows:SupportedCRS>urn:ogc:def:crs:EPSG::4498</ows:SupportedCRS>
		<TileMatrix>
			<ows:Identifier>EPSG:4498x2:0</ows:Identifier>
			<ScaleDenominator>4407822.984830845</ScaleDenominator>
			<TopLeftCorner>5895315.0 2.0184047248447325E7</TopLeftCorner>
			<TileWidth>512</TileWidth>
			<TileHeight>512</TileHeight>
			<MatrixWidth>1</MatrixWidth>
			<MatrixHeight>6</MatrixHeight>
		</TileMatrix>
		<TileMatrix>
			<ows:Identifier>EPSG:4498x2:1</ows:Identifier>
			<ScaleDenominator>2203911.4924154226</ScaleDenominator>
			<TopLeftCorner>5895315.0 2.0184047248447325E7</TopLeftCorner>
			<TileWidth>512</TileWidth>
			<TileHeight>512</TileHeight>
			<MatrixWidth>2</MatrixWidth>
			<MatrixHeight>12</MatrixHeight>
		</TileMatrix>
		<TileMatrix>
			<ows:Identifier>EPSG:4498x2:2</ows:Identifier>
			<ScaleDenominator>1101955.7462077113</ScaleDenominator>
			<TopLeftCorner>5737339.0 2.0184047248447325E7</TopLeftCorner>
			<TileWidth>512</TileWidth>
			<TileHeight>512</TileHeight>
			<MatrixWidth>4</MatrixWidth>
			<MatrixHeight>23</MatrixHeight>
		</TileMatrix>
		<TileMatrix>
			<ows:Identifier>EPSG:4498x2:3</ows:Identifier>
			<ScaleDenominator>550977.8731038556</ScaleDenominator>
			<TopLeftCorner>5737339.0 2.0184047248447325E7</TopLeftCorner>
			<TileWidth>512</TileWidth>
			<TileHeight>512</TileHeight>
			<MatrixWidth>8</MatrixWidth>
			<MatrixHeight>46</MatrixHeight>
		</TileMatrix>
		<TileMatrix>
			<ows:Identifier>EPSG:4498x2:4</ows:Identifier>
			<ScaleDenominator>275488.9365519278</ScaleDenominator>
			<TopLeftCorner>5737339.0 2.0184047248447325E7</TopLeftCorner>
			<TileWidth>512</TileWidth>
			<TileHeight>512</TileHeight>
			<MatrixWidth>16</MatrixWidth>
			<MatrixHeight>92</MatrixHeight>
		</TileMatrix>
		<TileMatrix>
			<ows:Identifier>EPSG:4498x2:5</ows:Identifier>
			<ScaleDenominator>137744.4682759639</ScaleDenominator>
			<TopLeftCorner>5717592.0 2.0184047248447325E7</TopLeftCorner>
			<TileWidth>512</TileWidth>
			<TileHeight>512</TileHeight>
			<MatrixWidth>32</MatrixWidth>
			<MatrixHeight>183</MatrixHeight>
		</TileMatrix>
		<TileMatrix>
			<ows:Identifier>EPSG:4498x2:6</ows:Identifier>
			<ScaleDenominator>68872.23413798196</ScaleDenominator>
			<TopLeftCorner>5717592.0 2.0184047248447325E7</TopLeftCorner>
			<TileWidth>512</TileWidth>
			<TileHeight>512</TileHeight>
			<MatrixWidth>64</MatrixWidth>
			<MatrixHeight>366</MatrixHeight>
		</TileMatrix>
		<TileMatrix>
			<ows:Identifier>EPSG:4498x2:7</ows:Identifier>
			<ScaleDenominator>34436.11706899098</ScaleDenominator>
			<TopLeftCorner>5717592.0 2.0184047248447325E7</TopLeftCorner>
			<TileWidth>512</TileWidth>
			<TileHeight>512</TileHeight>
			<MatrixWidth>128</MatrixWidth>
			<MatrixHeight>732</MatrixHeight>
		</TileMatrix>
		<TileMatrix>
			<ows:Identifier>EPSG:4498x2:8</ows:Identifier>
			<ScaleDenominator>17218.05853449549</ScaleDenominator>
			<TopLeftCorner>5715123.0 2.0184047248447325E7</TopLeftCorner>
			<TileWidth>512</TileWidth>
			<TileHeight>512</TileHeight>
			<MatrixWidth>256</MatrixWidth>
			<MatrixHeight>1463</MatrixHeight>
		</TileMatrix>
		<TileMatrix>
			<ows:Identifier>EPSG:4498x2:9</ows:Identifier>
			<ScaleDenominator>8609.029267247744</ScaleDenominator>
			<TopLeftCorner>5715123.0 2.0184047248447325E7</TopLeftCorner>
			<TileWidth>512</TileWidth>
			<TileHeight>512</TileHeight>
			<MatrixWidth>512</MatrixWidth>
			<MatrixHeight>2926</MatrixHeight>
		</TileMatrix>
		<TileMatrix>
			<ows:Identifier>EPSG:4498x2:10</ows:Identifier>
			<ScaleDenominator>4304.514633623872</ScaleDenominator>
			<TopLeftCorner>5714506.0 2.0184047248447325E7</TopLeftCorner>
			<TileWidth>512</TileWidth>
			<TileHeight>512</TileHeight>
			<MatrixWidth>1024</MatrixWidth>
			<MatrixHeight>5851</MatrixHeight>
		</TileMatrix>
		<TileMatrix>
			<ows:Identifier>EPSG:4498x2:11</ows:Identifier>
			<ScaleDenominator>2152.257316811936</ScaleDenominator>
			<TopLeftCorner>5714506.0 2.0184047248447325E7</TopLeftCorner>
			<TileWidth>512</TileWidth>
			<TileHeight>512</TileHeight>
			<MatrixWidth>2048</MatrixWidth>
			<MatrixHeight>11702</MatrixHeight>
		</TileMatrix>
		<TileMatrix>
			<ows:Identifier>EPSG:4498x2:12</ows:Identifier>
			<ScaleDenominator>1076.128658405968</ScaleDenominator>
			<TopLeftCorner>5714352.0 2.0184047248447325E7</TopLeftCorner>
			<TileWidth>512</TileWidth>
			<TileHeight>512</TileHeight>
			<MatrixWidth>4096</MatrixWidth>
			<MatrixHeight>23403</MatrixHeight>
		</TileMatrix>
		<TileMatrix>
			<ows:Identifier>EPSG:4498x2:13</ows:Identifier>
			<ScaleDenominator>538.064329202984</ScaleDenominator>
			<TopLeftCorner>5714275.0 2.0184047248447325E7</TopLeftCorner>
			<TileWidth>512</TileWidth>
			<TileHeight>512</TileHeight>
			<MatrixWidth>8192</MatrixWidth>
			<MatrixHeight>46805</MatrixHeight>
		</TileMatrix>
		<TileMatrix>
			<ows:Identifier>EPSG:4498x2:14</ows:Identifier>
			<ScaleDenominator>269.0321646014918</ScaleDenominator>
			<TopLeftCorner>5714236.0 2.0184047248447325E7</TopLeftCorner>
			<TileWidth>512</TileWidth>
			<TileHeight>512</TileHeight>
			<MatrixWidth>16384</MatrixWidth>
			<MatrixHeight>93609</MatrixHeight>
		</TileMatrix>
		<TileMatrix>
			<ows:Identifier>EPSG:4498x2:15</ows:Identifier>
			<ScaleDenominator>134.5160823007461</ScaleDenominator>
			<TopLeftCorner>5714217.0 2.0184047248447325E7</TopLeftCorner>
			<TileWidth>512</TileWidth>
			<TileHeight>512</TileHeight>
			<MatrixWidth>32768</MatrixWidth>
			<MatrixHeight>187217</MatrixHeight>
		</TileMatrix>
		<TileMatrix>
			<ows:Identifier>EPSG:4498x2:16</ows:Identifier>
			<ScaleDenominator>67.25804115037286</ScaleDenominator>
			<TopLeftCorner>5714207.0 2.0184047248447325E7</TopLeftCorner>
			<TileWidth>512</TileWidth>
			<TileHeight>512</TileHeight>
			<MatrixWidth>65536</MatrixWidth>
			<MatrixHeight>374433</MatrixHeight>
		</TileMatrix>
		<TileMatrix>
			<ows:Identifier>EPSG:4498x2:17</ows:Identifier>
			<ScaleDenominator>33.62902057518643</ScaleDenominator>
			<TopLeftCorner>5714207.0 2.0184047248447325E7</TopLeftCorner>
			<TileWidth>512</TileWidth>
			<TileHeight>512</TileHeight>
			<MatrixWidth>131072</MatrixWidth>
			<MatrixHeight>748866</MatrixHeight>
		</TileMatrix>
		<TileMatrix>
			<ows:Identifier>EPSG:4498x2:18</ows:Identifier>
			<ScaleDenominator>16.814510287593215</ScaleDenominator>
			<TopLeftCorner>5714207.0 2.0184047248447325E7</TopLeftCorner>
			<TileWidth>512</TileWidth>
			<TileHeight>512</TileHeight>
			<MatrixWidth>262144</MatrixWidth>
			<MatrixHeight>1497732</MatrixHeight>
		</TileMatrix>
		<TileMatrix>
			<ows:Identifier>EPSG:4498x2:19</ows:Identifier>
			<ScaleDenominator>8.407255143796787</ScaleDenominator>
			<TopLeftCorner>5714207.0 2.0184047248447325E7</TopLeftCorner>
			<TileWidth>512</TileWidth>
			<TileHeight>512</TileHeight>
			<MatrixWidth>524288</MatrixWidth>
			<MatrixHeight>2995464</MatrixHeight>
		</TileMatrix>
	</TileMatrixSet>
</Contents>
<ServiceMetadataURL xlink:href="http://localhost:9090/geoserver/gwc/service/wmts?SERVICE=wmts&REQUEST=getcapabilities&VERSION=1.0.0"/>
<ServiceMetadataURL xlink:href="http://localhost:9090/geoserver/gwc/service/wmts/rest/WMTSCapabilities.xml"/>

**Comment by Baikaler** [comment]
这是geoserver中自定义网格集后geowebcache.xml中的
<gridSet>
      <name>EPSG:4498x2</name>
      <srs>
        <number>4498</number>
      </srs>
      <extent>
        <coords>
          <double>2.0184047248447325E7</double>
          <double>2103881.962779923</double>
          <double>2.0815952751552675E7</double>
          <double>5714206.250336334</double>
        </coords>
      </extent>
      <alignTopLeft>false</alignTopLeft>
      <resolutions>
        <double>1234.1904357526364</double>
        <double>617.0952178763182</double>
        <double>308.5476089381591</double>
        <double>154.27380446907955</double>
        <double>77.13690223453978</double>
        <double>38.56845111726989</double>
        <double>19.284225558634944</double>
        <double>9.642112779317472</double>
        <double>4.821056389658736</double>
        <double>2.410528194829368</double>
        <double>1.205264097414684</double>
        <double>0.602632048707342</double>
        <double>0.301316024353671</double>
        <double>0.1506580121768355</double>
        <double>0.0753290060884177</double>
        <double>0.0376645030442089</double>
        <double>0.0188322515221044</double>
        <double>0.0094161257610522</double>
        <double>0.0047080628805261</double>
        <double>0.0023540314402631</double>
      </resolutions>
      <metersPerUnit>1.0</metersPerUnit>
      <pixelSize>2.8E-4</pixelSize>
      <scaleNames>
        <string>EPSG:4498x2:0</string>
        <string>EPSG:4498x2:1</string>
        <string>EPSG:4498x2:2</string>
        <string>EPSG:4498x2:3</string>
        <string>EPSG:4498x2:4</string>
        <string>EPSG:4498x2:5</string>
        <string>EPSG:4498x2:6</string>
        <string>EPSG:4498x2:7</string>
        <string>EPSG:4498x2:8</string>
        <string>EPSG:4498x2:9</string>
        <string>EPSG:4498x2:10</string>
        <string>EPSG:4498x2:11</string>
        <string>EPSG:4498x2:12</string>
        <string>EPSG:4498x2:13</string>
        <string>EPSG:4498x2:14</string>
        <string>EPSG:4498x2:15</string>
        <string>EPSG:4498x2:16</string>
        <string>EPSG:4498x2:17</string>
        <string>EPSG:4498x2:18</string>
        <string>EPSG:4498x2:19</string>
      </scaleNames>
      <tileHeight>512</tileHeight>
      <tileWidth>512</tileWidth>
      <yCoordinateFirst>true</yCoordinateFirst>
    </gridSet>

**Comment by songyumeng** [comment]
你现在得现象是什么，wmts getTile请求是否发出，回来得是否是512得瓦片？

**Comment by songyumeng** [comment]
能否提供在线的wmts服务地址

**Comment by Baikaler** [comment]
> 你现在得现象是什么，wmts getTile请求是否发出，回来得是否是512得瓦片？

返回的瓦片不在范围内，我们数据涉密，不能提供在线的

**Comment by songyumeng** [comment]
没有能调试的服务，我只能猜测下问题原因:

通过你设置的bounds :2.0184047248447325E7，2103881.962779923，2.0815952751552675E7，5714206.250336334 可得bounds宽度为631905.5031053498，高度为3610324.287556411。

**mapboxgl-enhance 内部的逻辑为，宽高的最大值/512为第0级的分辨率，即3610324.287556411/512=7051.414624133616。r然后用bounds的左上角和计算出的第0级分辨率，构建瓦片金字塔。**

但是该WMTS服务的0级分辨率为1234.1904357526364。这可能就是无法请求到正确瓦片的原因，并不是去请求了256的瓦片 。

你提供的WMTS的Capabilities的内容格式错乱了，猜测其中的5714352.0 2.0184047248447325E7是TopLeftCorner，即该WMTS服务的瓦片左上角。根据前面提到的mapboxgl-enhance 内部的逻辑，要让mapboxgl-enhance 内部的瓦片金字塔与你的WMTS服务的瓦片金字塔匹配，new CRS的bounds左上角需要是TopLeftCorner的值，即bounds应该调整为2.0184047248447325E7，2103881.962779923，2.0815952751552675E7，5714352.0

mapboxgl-enhance目前不支持自定义级别对应的分辨率。所以为了能出图只有尝试修改new CRS的bounds，让mapboxgl-enhance内部计算的瓦片金字塔0级分辨率与WMTS的0级分辨率对应上。在左上角固定的前提下，WMTS服务的第0级分辨率为1234.1904357526364，可知bounds的最大宽高都应该为1234.1904357526364*512=631905.5031053498。那bounds应该调整为2.0184047248447325E7，5082446.49689465，20815952.751552675，5714352.0。

这个bounds和本身服务的bounds差别很大，需要确定是否能完全包含你的数据，如果没有完全包含的话，就会出现地图加载不完整的情况。

综上：如果根据我的解释计算出的bounds能概括你的数据范围，可以尝试加载。如果没有完全包含，那目前mapboxgl-enhance无法加载你提供的这个服务。

mapboxgl-enhance支持自定义级别对应的分辨率的功能我们正在规划中。

不知道我解释的清不清楚，如需更详细交流可以拨打我们的技术支持电话400-8900-866。我们的技术团队会在电话中为您提供一对一的服务，确保您的问题得到妥善解决。
