### ISSUE TITLE
调用MapVLayer的clearData方法时报错

### ISSUE THREAD

**Issue by zhang6685979** [SuperMap/iClient-JavaScript#5]
报this.canvasLayer.setZIndex is not a function错误

**Comment by songyumeng** [comment]
谢谢你提的issue，可以提供更清楚的信息吗？（for leaflet，for ol，for mapboxgl还是iclient classic，重现步骤等），或者提供可重现的代码、文件。

**Comment by zhang6685979** [comment]
for mapboxgl

官网中的这个例子：(http://supermap.com:8090/iserver/iClient/forJavaScript/examples/mapboxgl/editor.html#mapvQianxi)
我想通过动态的数据渲染图层中的效果，数据更改时清除掉原有的数据重新渲染，但是在调用MapVLayer的clearData方法时报错

**Comment by songyumeng** [comment]
Fix by [2f13c74](https://github.com/SuperMap/iClient-JavaScript/commit/2f13c74a4de88f716d652c521e96178830b3df9c)

**Comment by songyumeng** [comment]
下个版本上线，或者使用 [dist](https://github.com/SuperMap/iClient-JavaScript/tree/master/dist) 下的临时版本
