### ISSUE TITLE
是否支持平面无投影数据

### ISSUE THREAD

**Issue by andypeibiao** [SuperMap/iClient-JavaScript#51]
### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]:
+ iClient version [iClient 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

----------

### Example of reproducing the issue [重现现象的例子]

----------

**Comment by songyumeng** [comment]
谢谢您提的issue，请参照issue模板提issue 或者 描述清楚以下细节，方便加快我们解决问题的速度：

iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]:
iClient version [iClient 版本]:
Actual Behavior [当前现象]
Expected Behavior [期望现象]
Example of reproducing the issue [重现现象的例子]
