### ISSUE TITLE
viewshed3d

### ISSUE THREAD

**Issue by lzp0070007** [SuperMap/iClient-JavaScript#54]
请问  ViewShed3D 
https://enonline.supermap.com/supermap_iclient3d_9.0.1_for_webgl/build/documentation/viewshed3d.html
的源码能开源吗？哪里能找到。。。

**Comment by songyumeng** [comment]
SuperMap iClient JavaScript（云GIS网络客户端开发平台） 和 SuperMap iClient3D for WebGL（三维客户端开发平台）是两条独立的产品线，后者并未开源，感谢您对超图产品的关注。
可以拨打超图支持中心400-8900-866电话，咨询SuperMap iClient3D for WebGL相关问题
