### ISSUE TITLE
加载矢量瓦片报错

### ISSUE THREAD

**Issue by Luooooooo** [SuperMap/iClient-JavaScript#57]
### Request a feature or report a bug? [这是一个需求还是一个缺陷]
缺陷
### One-line summary [问题简述]
加载矢量瓦片报错
### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]: iclient-openlayers 
+ iClient version [iClient 版本]:v10.0.0
+ Browser version [浏览器类型和版本]:谷歌78
+ OS Version [操作系统类型和版本]:win10

----------

### Actual Behavior [当前现象]
```
iclient-openlayers-es6.js:89071 Uncaught TypeError: Cannot read property 'applyBackground' of undefined
    at MapboxStyles_MapboxStyles._createStyleFunction (iclient-openlayers-es6.js:89071)
    at MapboxStyles_MapboxStyles._initStyleFunction (iclient-openlayers-es6.js:89062)
    at Image.img.onload (iclient-openlayers-es6.js:89044)
```
### Expected Behavior [期望现象]
矢量瓦片可以加载
### Example of reproducing the issue [重现现象的例子]
在本地
```
	var style_url = "http://47.104.186.12:8090/iserver/services/map-mvt-ZiShuiTu/restjsr/v1/vectortile/maps/渍水图/style.json"
	var format = new ol.format.MVT({
		featureClass: ol.Feature

	});
	var style = new ol.supermap.MapboxStyles({
		style: style_url,
		map: map
	})
	style.on('styleloaded', function () {
		console.log(style)
		var layer_risk = new ol.layer.VectorTile({
			declutter: true,
			source: new ol.source.VectorTileSuperMapRest({
				// url,
				style: style_url,
				projection: 'EPSG:3857',
				format: format
			}),
			style: style.getStyleFunction()
		});
		console.log(layer_risk)
		map.addLayer(layer_risk);
		layer_risk.setVisible(false);
	})
```

在官方demo加上请求的矢量瓦片

![微信截图_20191114182747](https://user-images.githubusercontent.com/29565303/68849535-3b5ad800-070d-11ea-8d15-69acadcab307.png)

----------
在iserver可以浏览
![微信截图_20191114182724](https://user-images.githubusercontent.com/29565303/68849559-444ba980-070d-11ea-88f2-ca5b68fb4c3c.png)

**Comment by acidgis** [comment]
感谢您的详细反馈，我们会尽快安排处理

**Comment by songyumeng** [comment]
谢谢您报的缺陷。
本地的报错是因为，矢量瓦片功能依赖`ol-debug`和`ol-mapbox-style`插件，
需要引入`http://iclient.supermap.io/web/libs/openlayers/plugins/ol-mapbox-style/2.11.2/olms.js`

官方demo的报错是因为，zoom为6的时候，您的矢量瓦片缓存中不存在该级别矢量瓦片，可以将zoom设置大一下，比如15。可以通过设置`view`的`minZoom`、 `maxZoom` 或者 `ol.layer.VectorTile`的`minResolution`、`maxResolution`控制可见级别

![image](https://user-images.githubusercontent.com/29563916/69022873-b1a25780-09f7-11ea-959f-f6268260e935.png)

**Comment by Luooooooo** [comment]
好的，谢谢
