### ISSUE TITLE
使用@supermap/iclient-leaflet初始化地图的时候少了一个css，导致样式乱

### ISSUE THREAD

**Issue by callmepinggege** [SuperMap/iClient-JavaScript#7]
我按照官方文档:

import L from 'leaflet';
import {tiledMapLayer} from '@supermap/iclient-leaflet';

var url = "http://support.supermap.com.cn:8090/iserver/services/map-world/rest/maps/World";
var map = L.map('map', {
    crs: L.CRS.EPSG4326,
    center: [0, 0],
    maxZoom: 18,
    zoom: 1
});
tiledMapLayer(url).addTo(map);

代码不会报错，地图出来了，但是样式不对，因为少了某个js，我通过官方源码对比找出来了那个css
<link rel="stylesheet" href="http://cdn.bootcss.com/leaflet/1.2.0/leaflet.css">  

希望你们能加到npm包里面去，这样我就不需要在外面应用一次，官网请说明下一下，不然别人第一次使用会以为你们产品有问题

**Comment by songyumeng** [comment]
谢谢你报issue。您这里说的缺少的 css 是 leaflet.css 吗？我们会修复官方文档，增加引入css的说明。

**Comment by callmepinggege** [comment]
<link rel="stylesheet" href="http://cdn.bootcss.com/leaflet/1.2.0/leaflet.css"> 这个

**Comment by songyumeng** [comment]
[http://iclient.supermap.io/web/introduction/leafletDevelop.html#Import](http://iclient.supermap.io/web/introduction/leafletDevelop.html#Import)
官方文档已修复。
