### ISSUE TITLE
9D Classic的mapv图层只支持4326坐标系和3857坐标系吗？我是北京54的坐标系，出不来图，有人知道这个是什么原因吗

### ISSUE THREAD

**Issue by fangchuanzhi** [SuperMap/iClient-JavaScript#8]
### One-line summary [问题简述]
9D Classic的mapv图层只支持4326坐标系和3857坐标系吗？我是北京54的坐标系，出不来图，有人知道这个是什么原因吗
### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]:
+ iClient version [iClient 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

----------

### Example of reproducing the issue [重现现象的例子]

----------

**Comment by songyumeng** [comment]
现状确实如此，仅支持4326,3857。我们会安排支持其他投影。
