### ISSUE TITLE
不能混用 import 以及 module.exports

### ISSUE THREAD

**Issue by zhangucan** [SuperMap/iClient-JavaScript#9]
### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]: for leaflet
+ iClient version [iClient 版本]: 当前master
+ Browser version [浏览器类型和版本]: node 8.9.4 
+ OS Version [操作系统类型和版本]: nuxt.js

----------

### Actual Behavior [当前现象]
` warning  in ./node_modules/@supermap/iclient-leaflet/overlay/TurfLayer.js`
`"export 'default' (imported as 'turf') was not found in '@turf/turf'`

### Example of reproducing the issue [重现现象的例子]

----------

**Comment by songyumeng** [comment]
可以贴出你的代码吗？我们修正的写法是  import * as turf from '@turf/turf'。这是可以解决问题的。
