### ISSUE TITLE
10i的mvt矢量瓦片标签文件有空格，造成文字长度超过背景

### ISSUE THREAD

**Issue by lwj2004gis** [SuperMap/iClient-JavaScript#96]
### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]:mapboxgl
+ iClient version [iClient 版本]:10i 
+ Browser version [浏览器类型和版本]:chrom
+ OS Version [操作系统类型和版本]:win10

----------

### Example of reproducing the issue [重现现象的例子]

----------

**Comment by acidgis** [comment]
问题确认：
使用的mapboxgl-gl-enhance.js
标签文字间没有空格，显示正常
标签文字间加了空格，标签无法完整显示

**Comment by songyumeng** [comment]
已修复，请获取最新[mapbox-gl-enhance.js](https://iclient.supermap.io/web/libs/mapbox-gl-js-enhance/1.2.0/mapbox-gl-enhance.js)。
