### ISSUE TITLE
editFeatures处理geojson生成的param不能正确解析featureCollection格式的数据

### ISSUE THREAD

**Issue by zhuxiangjian** [SuperMap/iClient-JavaScript#97]
### Request a feature or report a bug? [这是一个需求还是一个缺陷]
缺陷
### One-line summary [问题简述]
当使用geojson作为地物编辑的参数时，如果geojson是featureCollection，方法不能正常解析
### Version [产品及版本]
+ iClient product (for leaflet,for openlayers,for mapboxgl,classic)[iClient 产品]:for leaflet
+ iClient version [iClient 版本]: 10.0.0
+ Browser version [浏览器类型和版本]:谷歌
+ OS Version [操作系统类型和版本]:win

----------

### Actual Behavior [当前现象]
不能解析featureCollection类型的geojson中的属性信息
### Expected Behavior [期望现象]
能正常解析
### Example of reproducing the issue [重现现象的例子]

----------

**Comment by songyumeng** [comment]
谢谢您报的issue。
能否提供demo，或者调用接口的代码片段和featureCollection对象，以便我们更方便快速的定位和解决问题。
