### ISSUE TITLE
聚类图层-聚合点展开状态点击小点有概率使聚合点状态重置

### ISSUE THREAD

**Issue by qiangbro** [SuperMap/iClient-JavaScript#99]
### One-line summary [问题简述]
打开聚类图层的官方示例，点击一个聚合点，它会展开，变成一个一个小红点，单击小红点会弹出信息窗口，并且聚合点维持展开的情况（如图1）。
问题来了。单击一个小红点后，鼠标迅速移动到旁边的小红点，聚合点的状态有高概率重置为聚合状态，除刚才单击的小红点以外，其他小红点全都消失（如图2），必须重新点击聚合点，才能再次将所有的小红点展现出来。
![image](https://user-images.githubusercontent.com/4646469/70224731-bfdacc80-1788-11ea-8da3-06ae8f778c3a.png)
![image](https://user-images.githubusercontent.com/4646469/70224759-c8330780-1788-11ea-95f1-7891018f44c7.png)

### Version [产品及版本]
+ iClient classic: 10
+ Browser version [浏览器类型和版本]: chrome78
+ OS Version [操作系统类型和版本]: win7

----------

### Actual Behavior [当前现象]
单击一个小红点后，鼠标迅速移动到旁边的小红点，聚合点的状态有高概率重置为聚合状态，除之前单击的小红点以外，其他小红点全都消失。
### Expected Behavior [期望现象]
单击一个小红点后，鼠标迅速移动到旁边的小红点时，正常弹出信息窗口，并且聚合点始终维持展开的情况，其他小红点全都保持存在。
### Example of reproducing the issue [重现现象的例子]
http://iclient.supermap.io/examples/classic/editor.html#vizLayer_clusterLayer

----------

### What is motivation or use case for changing the behavior? [需求的场景和目的是什么？]
摄像头打点的聚散。

**Comment by qiangbro** [comment]
问题已查明，是由于判定click事件的鼠标坐标，使用的是判定非双击的结束时间时的鼠标位置，而不是初始触发单击时的鼠标位置。由于结束时间时的我的鼠标位置已经离开原来的红点，所以会导致错误的产生一个clickout事件，导致聚散点闭合。
希望以上分析有助于超图开发人员解决该问题。

**Comment by qiangbro** [comment]
今日联系了超图售后热线，已经确认了iclientclassic产品缺陷，对面能够复现，已报缺陷给研发中心处理，估计需要等一段时间才能修复。

**Comment by songyumeng** [comment]
已通过售后修复，提供iclient8C修复版本
